<?php
/**
 * Характеристики товара.
 *
 * @var umiTemplaterPHP|ViewPhpExtension|DemomarketPhpExtension $this
 * @var array $variables
 */

$product = $variables['page'];
?>


<div class="article">
	<h3 class="up"><?= $this->translate('product_properties_header') ?></h3>
	<table>
	<?php foreach ($this->getProductPropertyChunks($product) as $index => $chunk): ?>
		<?php foreach ($chunk as $property): if(empty($property['value'])) continue; ?>
			<tr>
			<td><?= $property['title'] ?></td>
			<td>
				<span umi:element-id="<?= $variables['pageId'] ?>" umi:field-name="<?= $property['name'] ?>"
					umi:empty="<?= $property['title'] ?>">
					<?= $property['value'] ?>
				</span>
			</td> 
			</tr>
		<?php endforeach; ?>	
	<?php endforeach; ?>
	</table>
</div> 