<?php
/**
 * Категория каталога товаров.
 *
 * @var umiTemplaterPHP|ViewPhpExtension|DemomarketPhpExtension $this
 * @var array $variables
 */
?>
<?php if ($variables['page']->getValue('shablon')): ?>
	<?= $this->render($variables, $variables['page']->getValue('shablon')) ?>
<?php else: ?>
	<div class="catalog">
		<?= $this->render($variables, 'catalog/category/caption') ?>

		<div class="container mobile_all_width d_flex">
			<?php if ($this->isInternalCategory($variables)): ?>
				<?= $this->render($variables, 'catalog/category/internal_category') ?>
			<?php else: ?>
				<?= $this->render($variables, 'catalog/category/leaf_category') ?>
			<?php endif; ?>
		</div>
	</div>
<?php endif; ?>