<?php
/**
 * Категория каталога товаров.
 *
 * @var umiTemplaterPHP|ViewPhpExtension|DemomarketPhpExtension $this
 * @var array $variables
 */
$catalog = $this->getChildCategories($variables);
$childCategoryList = $catalog['items'];
$catalog = $this->getCatalog($variables);
$productList = $this->getPages($catalog);
$pagination = $this->getPagination($catalog);
$this->setCommonVar('smart_filters', $this->getSmartFilters($variables));
?>
<?php if ($variables['page']->getValue('shablon')): ?>
	<?= $this->render($variables, $variables['page']->getValue('shablon')) ?>
<?php else: ?>

 

        <section class="pool-filters">
          <div class="center-wrap">
            <?= $this->render($variables, 'layout/header/titleWithBread') ?>
            <div class="pool-filters__list">
              <?php foreach ($childCategoryList as $category): ?>
                <a class="pool-filters__item" href="<?=$category->link?>">
                  <div class="pool-filters__item-img">
                    <div><img src="<?=$category->getValue('photo')?>" alt=""></div>
                  </div>
                  <div class="pool-filters__item-title"><?=$category->name?></div>
                </a>
              <?php endforeach; ?>
              
              <div class="pool-filters__item pool-filters__item--hide"></div>
              <div class="pool-filters__item pool-filters__item--hide"></div>
              <div class="pool-filters__item pool-filters__item--hide"></div>
            </div>
            <div class="pool-filters__sort">
              
              <div class="pool-filters__sort-left">
                <div class="pool-filters__sort-quantity">28 товаров</div>
                <?php if (!$this->isRootCatalog($variables)): $sort = ['price'=>'По цене','name'=>'По имени','ord'=>'По умолчанию']; ?>
                <span class="pool-filters__sort-title">Сортировать</span>
                <div class="select">
                  <div class="select__value">
                    <svg class="select__down" width="15" height="13" viewBox="0 0 15 13" fill="none" xmlns="http://www.w3.org/2000/svg">
                      <path d="M3.18046 9.67654C3.18046 9.8537 3.18046 10.7526 3.18046 10.7526C3.18046 10.7526 2.35824 10.1648 2.14087 10.001C1.90305 9.8218 1.402 9.9088 1.16418 10.088C0.862591 10.3152 0.862591 10.6837 1.16418 10.9109L2.92667 12.2389C3.93656 13.0631 3.93656 13.0631 4.94645 12.2389L6.70894 10.9109C7.01053 10.6837 7.01053 10.3152 6.70894 10.088C6.47112 9.9088 5.97007 9.8218 5.73225 10.001C5.51488 10.1648 4.69266 10.7526 4.69266 10.7526C4.69266 10.7526 4.69266 9.8537 4.69266 9.67654V1.47919C4.69266 1.16455 4.35414 0.909485 3.93656 0.909485C3.51897 0.909485 3.18046 1.16455 3.18046 1.47919V9.67654Z"></path>
                      <path d="M15 1.95252C15 1.4812 14.7385 1.09912 14.4159 1.09912H7.93256C7.60998 1.09912 7.34847 1.4812 7.34847 1.95252C7.34847 2.42384 7.60998 2.80591 7.93256 2.80591H14.4159C14.7385 2.80591 15 2.42384 15 1.95252Z"></path>
                      <path d="M15 6.97806C15 6.55911 14.7437 6.21948 14.4276 6.21948H9.16165C8.84553 6.21948 8.58926 6.55911 8.58926 6.97806C8.58926 7.39701 8.84553 7.73663 9.16165 7.73663H14.4276C14.7437 7.73663 15 7.39701 15 6.97806Z"></path>
                      <path d="M15 12.0036C15 11.5323 14.7412 11.1502 14.4219 11.1502H10.2014C9.8821 11.1502 9.62325 11.5323 9.62325 12.0036C9.62325 12.4749 9.8821 12.857 10.2014 12.857H14.4219C14.7412 12.857 15 12.4749 15 12.0036Z"></path>
                    </svg>
                    <div><?=$sort[$this->getSortField()]?></div>
                  </div>
                  <svg class="select__arrow" width="6" height="4" viewBox="0 0 6 4" fill="none" xmlns="http://www.w3.org/2000/svg">
                    <path d="M2.86243 4L0.643236 0.25L5.08162 0.25L2.86243 4Z"></path>
                  </svg>
                  <div class="select__variants">
                    <label class="select__variant <?= $this->getSortClass('price') ?>" for="" data-field="price"><span>По цене</span></label>
                    <label class="select__variant <?= $this->getSortClass('name') ?>" for="" data-field="name"><span>По имени</span></label>
                    <label class="select__variant <?= $this->getSortClass('ord') ?>" for="" data-field="ord"><span>По умолчанию</span></label>
                  </div>
                </div>
                <?php endif; ?>
              </div>
              
              <div class="pool-filters__sort-right">
                <!-- <span class="pool-filters__sort-title">Показывать по</span>
                <div class="select">
                  <div class="select__value">
                    <div>12</div>
                  </div>
                  <svg class="select__arrow" width="6" height="4" viewBox="0 0 6 4" fill="none" xmlns="http://www.w3.org/2000/svg">
                    <path d="M2.86243 4L0.643236 0.25L5.08162 0.25L2.86243 4Z"></path>
                  </svg>
                  <div class="select__variants">
                    <label class="select__variant select__variant--active" for=""><span>03</span></label>
                    <label class="select__variant" for=""><span>04</span></label>
                    <label class="select__variant" for=""><span>05</span></label>
                  </div>
                </div> -->
               
                <a class="pool-filters__position" data-class="goods">
                  <svg width="23" height="20" viewBox="0 0 23 20" fill="none" xmlns="http://www.w3.org/2000/svg">
                    <path d="M4.99913 0H0.578125V4H4.99913V0Z"></path>
                    <path d="M4.99913 8H0.578125V12H4.99913V8Z"></path>
                    <path d="M4.99913 16H0.578125V20H4.99913V16Z"></path>
                    <path d="M13.8414 0H9.42041V4H13.8414V0Z"></path>
                    <path d="M13.8414 8H9.42041V12H13.8414V8Z"></path>
                    <path d="M9.42041 16H13.8414V20H9.42041V16Z"></path>
                    <path d="M22.6832 0H18.2622V4H22.6832V0Z"></path>
                    <path d="M22.6832 8H18.2622V12H22.6832V8Z"></path>
                    <path d="M22.6832 16H18.2622V20H22.6832V16Z"></path>
                  </svg>
                </a>
                <a class="pool-filters__position pool-filters__position--active" data-class="catalog_list">
                  <svg width="21" height="16" viewBox="0 0 21 16" fill="none" xmlns="http://www.w3.org/2000/svg">
                    <path d="M20.7358 0H0.841309V2H20.7358V0Z"></path>
                    <path d="M20.7358 7H0.841309V9H20.7358V7Z"></path>
                    <path d="M20.7358 14H0.841309V16H20.7358V14Z"></path>
                  </svg>
                </a>
              
              </div>
            </div>
            <div class="pool-filters__filter">
              <?= $this->render($variables, 'catalog/category/filters/index') ?>
              
              <!-- <div class="pool-filters__filter-right">
                <div class="select">
                  <div class="select__value">
                    <div>Мои фильтры</div>
                  </div>
                  <svg class="select__arrow" width="6" height="4" viewBox="0 0 6 4" fill="none" xmlns="http://www.w3.org/2000/svg">
                    <path d="M2.86243 4L0.643236 0.25L5.08162 0.25L2.86243 4Z"></path>
                  </svg>
                  <div class="select__variants">
                    <label class="select__variant select__variant--active" for=""><span>03</span></label>
                    <label class="select__variant" for=""><span>04</span></label>
                    <label class="select__variant" for=""><span>05</span></label>
                  </div>
                </div>
                <div class="pool-filters__filter-save">
                  <svg width="14" height="14" viewBox="0 0 14 14" fill="none" xmlns="http://www.w3.org/2000/svg">
                    <path d="M11.9843 0H1.64062C0.735984 0 0 0.735984 0 1.64062V12.3594C0 13.264 0.735984 14 1.64062 14H12.3594C13.264 14 14 13.264 14 12.3594V2.01567L11.9843 0ZM3.28125 1.09375H9.57031V4.32031H3.28125V1.09375ZM10.7188 12.9062H3.28125V8.58594H10.7188V12.9062ZM12.9062 12.3594C12.9062 12.6609 12.6609 12.9062 12.3594 12.9062H11.8125V7.49219H2.1875V12.9062H1.64062C1.33908 12.9062 1.09375 12.6609 1.09375 12.3594V1.64062C1.09375 1.33908 1.33908 1.09375 1.64062 1.09375H2.1875V5.41406H10.6641V1.09375H11.5313L12.9062 2.4687V12.3594Z"></path>
                  </svg>Сохранить
                </div>
              </div> -->
            </div>
            <div class="pool-filters__wrap goods" id="catalog_category">
              <?php foreach ($productList as $product): ?>
                <?= $this->render($product, 'catalog/product/preview/index') ?>
              <?php endforeach; ?>
              <div class="card" style="opacity:0;padding: 0;margin: 0;"></div>
              <div class="card" style="opacity:0;padding: 0;margin: 0;"></div>
              <div class="card" style="opacity:0;padding: 0;margin: 0;"></div>
              <div class="card" style="opacity:0;padding: 0;margin: 0;"></div>
            </div>
          </div>
        </section>

        <?php /*
        <section class="collection collection--catalog">
          <div class="center-wrap">
            <div class="simple-title collection__title">Коллекции</div>
            <div class="collection__list mobile--hide"><a class="collection__item" href="">
                <div class="collection__img">
                  <div><img src="assets/images/collection__img3.png" alt=""></div><span class="collection__img-oval"></span>
                </div>
                <div class="collection__item-title">Испанская фильтрация 2020 года</div></a><a class="collection__item collection__item--hide" href=""></a><a class="collection__item collection__item--hide" href=""></a><a class="collection__item collection__item--hide" href=""></a><a class="collection__item collection__item--hide" href=""></a>
            </div>
            <div class="collection-slider desktop--hide">
              <div class="swiper-container">
                <div class="swiper-wrapper">
                  <div class="swiper-slide">
                    <div class="collection__item">
                      <div class="collection__img">
                        <div><img src="assets/images/collection__img3.png" alt=""></div><span class="collection__img-oval"></span>
                      </div><a class="collection__item-title" href="">Испанская фильтрация 2020 года</a>
                    </div>
                  </div>
                  <div class="swiper-slide">
                    <div class="collection__item">
                      <div class="collection__img">
                        <div><img src="assets/images/collection__img3.png" alt=""></div><span class="collection__img-oval"></span>
                      </div><a class="collection__item-title" href="">Испанская фильтрация 2020 года</a>
                    </div>
                  </div>
                  <div class="swiper-slide">
                    <div class="collection__item">
                      <div class="collection__img">
                        <div><img src="assets/images/collection__img3.png" alt=""></div><span class="collection__img-oval"></span>
                      </div><a class="collection__item-title" href="">Испанская фильтрация 2020 года</a>
                    </div>
                  </div>
                  <div class="swiper-slide">
                    <div class="collection__item">
                      <div class="collection__img">
                        <div><img src="assets/images/collection__img3.png" alt=""></div><span class="collection__img-oval"></span>
                      </div><a class="collection__item-title" href="">Испанская фильтрация 2020 года</a>
                    </div>
                  </div>
                  <div class="swiper-slide">
                    <div class="collection__item">
                      <div class="collection__img">
                        <div><img src="assets/images/collection__img3.png" alt=""></div><span class="collection__img-oval"></span>
                      </div><a class="collection__item-title" href="">Испанская фильтрация 2020 года</a>
                    </div>
                  </div>
                  <div class="swiper-slide">
                    <div class="collection__item">
                      <div class="collection__img">
                        <div><img src="assets/images/collection__img3.png" alt=""></div><span class="collection__img-oval"></span>
                      </div><a class="collection__item-title" href="">Испанская фильтрация 2020 года</a>
                    </div>
                  </div>
                  <div class="swiper-slide">
                    <div class="collection__item">
                      <div class="collection__img">
                        <div><img src="assets/images/collection__img3.png" alt=""></div><span class="collection__img-oval"></span>
                      </div><a class="collection__item-title" href="">Испанская фильтрация 2020 года</a>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
     </section>
     */ ?>
<?php endif; ?>