<?php
    $page = $variables['page'];
    $catalog = $this->getChildCategories($variables);
    $childCategoryList = $catalog['items'];
    

    $settings = $this->getSettingsContainer();
    $populyarnye_kategorii = $settings->getValue('populyarnye_kategorii');

?>
<section class="building-pools" id="building-pools">
  <?=$this->render($variables, 'catalog/index/slider_block') ?>
</section>
<?=$this->render($variables, 'catalog/blocks/recently') ?>
<section class="popular-categories">
  <div class="center-wrap">
    <div class="simple-title popular-categories__title">Популярные категории</div>
    <div class="popular-categories__wrap mobile--hide">      
      <div class="popular-categories__list">
          <?php foreach($populyarnye_kategorii as $category){ ?>
            <a class="categorie" href="<?=$category->link?>">
              <div class="categorie__img">
                <div><img src="<?=$this->getPhotoPath($category)?>" alt=""></div>
              </div>
              <div class="categorie__title"><?=$category->name?></div>
            </a>
          <?php } ?>  
      <a class="categorie categorie--hide" href=""></a><a class="categorie categorie--hide" href=""></a></div>
      <div class="popular-categories__banner">
        <div class="banner">
          <div><img src="dist/assets/images/banner.png" alt=""></div>
        </div>
      </div>
    </div>
  </div>
  <div class="categories-slider desktop--hide">
    <div class="swiper-container">
      <div class="swiper-wrapper">
        <?php foreach($populyarnye_kategorii as $category){ ?>
            <div class="swiper-slide">
              <a class="categorie" href="<?=$category->link?>">
                <div class="categorie__img">
                  <div><img src="<?=$this->getPhotoPath($category)?>" alt=""></div>
                </div>
                <div class="categorie__title"><?=$category->name?></div>
              </a>
            </div>
          <?php } ?>
      </div>
    </div>
  </div>
</section>
        

<?=$this->render($variables, 'catalog/blocks/best') ?> 

<!-- 
        <section class="collection collection--build">
          <div class="center-wrap">
            <div class="simple-title collection__title">Коллекции</div>
            <div class="collection__list mobile--hide"><a class="collection__item" href="">
                <div class="collection__img">
                  <div><img src="dist/assets/images/collection__img1.png" alt=""></div><span class="collection__img-oval"></span>
                </div>
                <div class="collection__item-title">Топ-10 лучших роботов-пылесосов</div></a><a class="collection__item" href="">
                <div class="collection__img">
                  <div><img src="dist/assets/images/collection__img2.png" alt=""></div><span class="collection__img-oval"></span>
                </div>
                <div class="collection__item-title">Распродажа<br> химии для бассейна</div></a><a class="collection__item collection__item--hide" href=""></a><a class="collection__item collection__item--hide" href=""></a><a class="collection__item collection__item--hide" href=""></a>
            </div>
            <div class="collection-slider desktop--hide">
              <div class="swiper-container">
                <div class="swiper-wrapper">
                  <div class="swiper-slide">
                    <div class="collection__item">
                      <div class="collection__img">
                        <div><img src="dist/assets/images/collection__img1.png" alt=""></div><span class="collection__img-oval"></span>
                      </div><a class="collection__item-title" href="">Топ-10 лучших роботов-пылесосов</a>
                    </div>
                  </div>
                  <div class="swiper-slide">
                    <div class="collection__item">
                      <div class="collection__img">
                        <div><img src="dist/assets/images/collection__img2.png" alt=""></div><span class="collection__img-oval"></span>
                      </div><a class="collection__item-title" href="">Распродажа<br> химии для бассейна</a>
                    </div>
                  </div>
                  <div class="swiper-slide">
                    <div class="collection__item">
                      <div class="collection__img">
                        <div><img src="dist/assets/images/collection__img1.png" alt=""></div><span class="collection__img-oval"></span>
                      </div><a class="collection__item-title" href="">Топ-10 лучших роботов-пылесосов</a>
                    </div>
                  </div>
                  <div class="swiper-slide">
                    <div class="collection__item">
                      <div class="collection__img">
                        <div><img src="dist/assets/images/collection__img2.png" alt=""></div><span class="collection__img-oval"></span>
                      </div><a class="collection__item-title" href="">Распродажа<br> химии для бассейна</a>
                    </div>
                  </div>
                  <div class="swiper-slide">
                    <div class="collection__item">
                      <div class="collection__img">
                        <div><img src="dist/assets/images/collection__img2.png" alt=""></div><span class="collection__img-oval"></span>
                      </div><a class="collection__item-title" href="">Распродажа<br> химии для бассейна</a>
                    </div>
                  </div>
                  <div class="swiper-slide">
                    <div class="collection__item">
                      <div class="collection__img">
                        <div><img src="dist/assets/images/collection__img2.png" alt=""></div><span class="collection__img-oval"></span>
                      </div><a class="collection__item-title" href="">Распродажа<br> химии для бассейна</a>
                    </div>
                  </div>
                  <div class="swiper-slide">
                    <div class="collection__item">
                      <div class="collection__img">
                        <div><img src="dist/assets/images/collection__img2.png" alt=""></div><span class="collection__img-oval"></span>
                      </div><a class="collection__item-title" href="">Распродажа<br> химии для бассейна</a>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section> -->