<?php
    $page = $variables['page'];
    $catalog = $this->getChildCategories($variables);
    $childCategoryList = $catalog['items'];

    $action = $this->getCommonVar('pre_lang') . '/search/search_do/';
    

    $settings = $this->getSettingsContainer();
    $populyarnye_kategorii = $settings->getValue('populyarnye_kategorii');

?>
<?php if($this->isMobile()): ?>
<div class="search_wrapper">
  <form class="search search_mobile" action="<?= $action ?>" id="searchForm">
      <input class="search__input" type="search" name="search_string"	autocomplete="off" class="tooltip_toggle" placeholder="Поиск по каталогу" value="<?=(!empty($_GET['search_string'])?$_GET['search_string']:'')?>">
      <button class="search_mobile_button" type="submit">
        <svg width="15" height="15" viewBox="0 0 15 15" fill="none" xmlns="http://www.w3.org/2000/svg">
          <path d="M6.10008 0.434753C9.22905 0.434753 11.7656 2.97129 11.7656 6.10026C11.7656 7.39211 11.3332 8.58297 10.6053 9.53603L14.1882 13.1201C14.4832 13.4151 14.4832 13.8934 14.1882 14.1884C13.9159 14.4607 13.4874 14.4817 13.1911 14.2513L13.1199 14.1884L9.53584 10.6055C8.58279 11.3334 7.39193 11.7658 6.10008 11.7658C2.9711 11.7658 0.43457 9.22924 0.43457 6.10026C0.43457 2.97129 2.9711 0.434753 6.10008 0.434753ZM6.10008 1.94556C3.8055 1.94556 1.94537 3.80568 1.94537 6.10026C1.94537 8.39484 3.8055 10.255 6.10008 10.255C8.39466 10.255 10.2548 8.39484 10.2548 6.10026C10.2548 3.80568 8.39466 1.94556 6.10008 1.94556Z" fill="#84898E"/>
        </svg>
      </button>
  </form>
</div>
<?php endif;?>
<section class="building-pools" id="building-pools">
  <?=$this->render($variables, 'catalog/index/slider_block') ?>
</section>
<?=$this->render($variables, 'catalog/blocks/recently') ?>
<section class="popular-categories">
  <div class="center-wrap">
    <div class="simple-title popular-categories__title">Популярные категории</div>
    <div class="popular-categories__wrap mobile--hide">      
      <div class="popular-categories__list">
          <?php foreach($populyarnye_kategorii as $category){ ?>
            <a class="categorie" href="<?=$category->link?>">
              <div class="categorie__img">
                <div><img src="<?=$this->getPhotoPath($category)?>" alt=""></div>
              </div>
              <div class="categorie__title"><?=$category->name?></div>
            </a>
          <?php } ?>  
      <a class="categorie categorie--hide" href=""></a><a class="categorie categorie--hide" href=""></a></div>
      <div class="popular-categories__banner">
        <div class="banner">
          <div><img src="dist/assets/images/banner.png" alt=""></div>
        </div>
      </div>
    </div>
  </div>
  <div class="categories-slider desktop--hide">
    <div class="swiper-container">
      <div class="swiper-wrapper">
        <?php foreach($populyarnye_kategorii as $category){ ?>
            <div class="swiper-slide">
              <a class="categorie" href="<?=$category->link?>">
                <div class="categorie__img">
                  <div><img src="<?=$this->getPhotoPath($category)?>" alt=""></div>
                </div>
                <div class="categorie__title"><?=$category->name?></div>
              </a>
            </div>
          <?php } ?>
      </div>
    </div>
  </div>
</section>
        

<?=$this->render($variables, 'catalog/blocks/best') ?> 

<!-- 
        <section class="collection collection--build">
          <div class="center-wrap">
            <div class="simple-title collection__title">Коллекции</div>
            <div class="collection__list mobile--hide"><a class="collection__item" href="">
                <div class="collection__img">
                  <div><img src="dist/assets/images/collection__img1.png" alt=""></div><span class="collection__img-oval"></span>
                </div>
                <div class="collection__item-title">Топ-10 лучших роботов-пылесосов</div></a><a class="collection__item" href="">
                <div class="collection__img">
                  <div><img src="dist/assets/images/collection__img2.png" alt=""></div><span class="collection__img-oval"></span>
                </div>
                <div class="collection__item-title">Распродажа<br> химии для бассейна</div></a><a class="collection__item collection__item--hide" href=""></a><a class="collection__item collection__item--hide" href=""></a><a class="collection__item collection__item--hide" href=""></a>
            </div>
            <div class="collection-slider desktop--hide">
              <div class="swiper-container">
                <div class="swiper-wrapper">
                  <div class="swiper-slide">
                    <div class="collection__item">
                      <div class="collection__img">
                        <div><img src="dist/assets/images/collection__img1.png" alt=""></div><span class="collection__img-oval"></span>
                      </div><a class="collection__item-title" href="">Топ-10 лучших роботов-пылесосов</a>
                    </div>
                  </div>
                  <div class="swiper-slide">
                    <div class="collection__item">
                      <div class="collection__img">
                        <div><img src="dist/assets/images/collection__img2.png" alt=""></div><span class="collection__img-oval"></span>
                      </div><a class="collection__item-title" href="">Распродажа<br> химии для бассейна</a>
                    </div>
                  </div>
                  <div class="swiper-slide">
                    <div class="collection__item">
                      <div class="collection__img">
                        <div><img src="dist/assets/images/collection__img1.png" alt=""></div><span class="collection__img-oval"></span>
                      </div><a class="collection__item-title" href="">Топ-10 лучших роботов-пылесосов</a>
                    </div>
                  </div>
                  <div class="swiper-slide">
                    <div class="collection__item">
                      <div class="collection__img">
                        <div><img src="dist/assets/images/collection__img2.png" alt=""></div><span class="collection__img-oval"></span>
                      </div><a class="collection__item-title" href="">Распродажа<br> химии для бассейна</a>
                    </div>
                  </div>
                  <div class="swiper-slide">
                    <div class="collection__item">
                      <div class="collection__img">
                        <div><img src="dist/assets/images/collection__img2.png" alt=""></div><span class="collection__img-oval"></span>
                      </div><a class="collection__item-title" href="">Распродажа<br> химии для бассейна</a>
                    </div>
                  </div>
                  <div class="swiper-slide">
                    <div class="collection__item">
                      <div class="collection__img">
                        <div><img src="dist/assets/images/collection__img2.png" alt=""></div><span class="collection__img-oval"></span>
                      </div><a class="collection__item-title" href="">Распродажа<br> химии для бассейна</a>
                    </div>
                  </div>
                  <div class="swiper-slide">
                    <div class="collection__item">
                      <div class="collection__img">
                        <div><img src="dist/assets/images/collection__img2.png" alt=""></div><span class="collection__img-oval"></span>
                      </div><a class="collection__item-title" href="">Распродажа<br> химии для бассейна</a>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section> -->