<?php
/**
 * Поле умных фильтров типа "Дата".
 *
 * @var umiTemplaterPHP|ViewPhpExtension|DemomarketPhpExtension $this
 * @var array $variables
 */

$data = $this->getDateFilterFieldData($variables);
?>
<div class="select date_field">
	<div class="select__value">
	<div><?= $data['title'] ?></div>
	</div>
	<svg class="select__arrow" width="6" height="4" viewBox="0 0 6 4" fill="none" xmlns="http://www.w3.org/2000/svg">
	<path d="M2.86243 4L0.643236 0.25L5.08162 0.25L2.86243 4Z"></path>
	</svg>
	<div class="select__variants progress_hide">
		<div class="col-md-12 delta_price clearfix">
			<input type="text" name="<?= $data['name_from'] ?>" value="<?= $data['selected_min'] ?>"
				   data-minimum="<?= $data['min'] ?>" data-maximum="<?= $data['max'] ?>" class="min float_left" />

			<span>&mdash;</span>

			<input type="text" name="<?= $data['name_to'] ?>" value="<?= $data['selected_max'] ?>"
				   data-minimum="<?= $data['min'] ?>" data-maximum="<?= $data['max'] ?>" class="max float_right" />
		</div>
	</div>
</div>