<?php
/**
 * Контент новости.
 *
 * @var umiTemplaterPHP|ViewPhpExtension|DemomarketPhpExtension $this
 * @var array $variables
 * @var iUmiHierarchyElement $newsItem
 */

$newsItem = $variables['page'];
?>
   
<div class="center-wrap pt-2">
    <?= $this->render($variables, 'layout/header/titleWithBread') ?>
</div>

<div class="center-wrap pt-2">
    <div class="article pt-2">
        <?=$newsItem->getValue('content')?>
    </div>
</div>
