<?php
/**
 * Блок "С этим товаром покупают".
 *
 * @var umiTemplaterPHP|ViewPhpExtension|DemomarketPhpExtension $this
 * @var array $variables
 */

$product = $variables['page'];
$productList = $this->getSuggestedProducts($product);
?>

<?php if ($productList): ?>
	<section class="history">
        <div class="center-wrap">
        <h3 class="simple-title history__title"><?= $this->translate('suggested_products') ?></h3>
        <div class="history__list mobile--hide">
            
            <?php foreach ($productList as $product): ?>
                <?= $this->render($product, 'catalog/product/preview/index') ?>
            <?php endforeach; ?>
            <div class="pool-filters__item pool-filters__item--hide"></div>
					<div class="pool-filters__item pool-filters__item--hide"></div>
					<div class="pool-filters__item pool-filters__item--hide"></div>

        </div>
        </div>
        <div class="history-slider desktop--hide">
        <div class="swiper-container">
            <div class="swiper-wrapper">
            <?php foreach ($productList as $product): ?>
                <div class="swiper-slide"><?= $this->render($product, 'catalog/product/preview/index') ?></div>
            <?php endforeach; ?>
            </div>
        </div>
        </div>
    </section>
<?php endif; ?>


