<?php
/**
 * Поле типа "Строка".
 *
 * @var umiTemplaterPHP|ViewPhpExtension|DemomarketPhpExtension $this
 * @var array $field
 */

$field = $variables;
?>

<div class="inputs__field-wrap">
	<input class="inputs__field" type="<?= $this->getFieldTypeAttribute($field) ?>" name="<?= $field['input_name'] ?>" <?= (isset($field['required']) ? ' required ' : '') ?> value="<?= isset($field['value']) ? $field['value'] : '' ?>">
	<label class="inputs__label" for="text"><span class="inputs__content"><?= $field['title'] ?></span></label>
</div>