<?php
/**
 * Поле типа "Текст".
 *
 * @var umiTemplaterPHP|ViewPhpExtension|DemomarketPhpExtension $this
 * @var array $variables
 */

$field = $variables;
?>

<textarea
	name="<?= $field['input_name'] ?>"
    class="data-form__input_type_text"
	placeholder="<?= $field['title'] ?>"
	<?= isset($field['required']) ? ' required ' : '' ?>
><?= isset($field['value']) ? $field['value'] : '' ?></textarea>

<span class="sub_text"><?= $field['title'] ?></span>
