<?php
/**
 * Вспомогательный шаблон для построения динамических форм.
 * Отрисовывает каждую группу формы и каждое поле группы, в зависимости от типа данных поля.
 *
 * @var umiTemplaterPHP|ViewPhpExtension|DemomarketPhpExtension $this
 * @var array $variables
 * @var array $groupList
 */

$groupList = $variables['form']['groups'];
$groupList[1]['displayHeader']=0;
?>

<?php foreach ($groupList as $group): ?>
<div class="data-form">
    <?php
    if($group['title']=='Контакты') $variables['displayHeader']=false;
    ?>
	<?php if ($this->canShowGroupTitle($variables)): ?>
		<span class="data-form__title">
			<?= $group['title'] ?>
			
		</span>
	<?php endif; ?>

	<?php foreach ($this->getSubGroupList($group) as $subGroup): ?>
		<div class="">
			<?php foreach ($subGroup as $field): ?>
				<div class="<?= $this->getFormFieldClass($field) ?>">
					<?= $this->render($field, "data/form_field/{$field['type']}") ?>
				</div>
			<?php endforeach; ?>
		</div>
	<?php endforeach; ?>
</div>
<?php endforeach; ?>

