<?php
$p = $variables['page'];
$pic = $p->getValue('header_pic');
$header = $this->escape($variables['header']);

$models = [];
$modelsArr = $this->vsk_objByType(267);
foreach($modelsArr as $item){
    $models[$item->getValue('group')][] = $item;
}
$params = $this->vsk_objByType(265,false,9999);
$groups = $this->vsk_objByType(263);
$sections = $this->vsk_objByType(262);
$actions = [122208=>'show_section',122209=>'show_popup'];
$json = [];
$temp = [];
foreach($params as $param){
    $groupId = $param->getValue('gruppa');
    $temp[$groupId][$param->getId()]['name'] = $param->getName();
    $temp[$groupId][$param->getId()]['hint'] = $param->getValue('podskazka');
    $temp[$groupId][$param->getId()]['img'] = (!empty($param->getValue('kartinka')))?$param->getValue('kartinka')->getFilePath(1):'';
    // $temp[$groupId][$param->getId()]['prices'] = $param->getValue('param_prices');
    foreach($param->getValue('param_prices') as $price){
        $temp[$groupId][$param->getId()]['prices'][$this->vsk_objById($price['rel'])->name] = $price['float'];
    }
}
foreach($groups as $group){
    $json[$group->getValue('razdel')]['groups'][$group->getId()]['items'] = $temp[$group->getId()];
    $json[$group->getValue('razdel')]['groups'][$group->getId()]['icon'] = (!empty($group->getValue('icon')))?$group->getValue('icon')->getFilePath(1):'';
    $json[$group->getValue('razdel')]['groups'][$group->getId()]['hint'] = $group->getValue('hint');
    $json[$group->getValue('razdel')]['groups'][$group->getId()]['action'] = $actions[$group->getValue('action')];
    $json[$group->getValue('razdel')]['groups'][$group->getId()]['name'] = $group->getName();
    $json[$group->getValue('razdel')]['groups'][$group->getId()]['target_section'] = $group->getValue('show_razdel');
}
foreach($sections as $section){
    $json[$section->getId()]['name'] = $section->getName();
    $json[$section->getId()]['hide'] = $section->getValue('hide');
}
foreach($modelsArr as $category){
    $model = $category->getValue('model')[0];
    $price = intval(str_replace(' ', '', $model->getValue('stoimost')));
    $price_cristal = intval(str_replace(' ', '', $model->getValue('cena_cristal')));
    $model_width = $model->getValue('shirina');
    $model_length = $model->getValue('dlina');
    $model_depth = $model->getValue('glubina'); 
    $json['models'][$category->name]['price'] = ($price)?$price:false;
    $json['models'][$category->name]['cristal'] = ($price_cristal)?$price_cristal:false;
    $json['models'][$category->name]['width'] = ($model_width)?$model_width . ' м':false;
    $json['models'][$category->name]['length'] = ($model_length)?$model_length . ' м':false;
    $json['models'][$category->name]['depth'] = ($model_depth)?$model_depth . ' м':false;
//    $json['models'][$category->name]['difference'] = ($price_cristal>$price)?$price_cristal-$price:false;
}
?>

<div class="center-wrap" style="padding-top: 2.1rem;">
    <?= $this->render($variables, 'layout/header/titleWithBread') ?>
</div>

<div class="center-wrap" style="padding-top: 2.1rem;">
    <div class="configurator">
        <script>
            window.json = <?=json_encode($json)?>;
            console.log(window.json);
        </script>
        <div class="configurator__options">
            <div class="configurator__option configurator__option--active">
                <h6 class="configurator__option-header">Моделька</h6> 
                <div class="pool_window">
                    
                </div>
            </div>
            <div class="configurator__option configurator__option--active option_variant">
                <h6 class="configurator__option-header">Вариант исполнения</h6>
                <div class="configurator__option-window configurator__option-window_modified">
                    <div class="info_icon-container">
                        <svg class="info_icon" width="19" height="19" viewBox="0 0 19 19" xmlns="http://www.w3.org/2000/svg">
                            <circle cx="9.29319" cy="9.29319" r="8.79319" fill="white" />
                            <path d="M8.47921 7.23784H10.38L10.304 14.2077H8.40318L8.47921 7.23784ZM9.4372 5.89969C9.09253 5.89969 8.80361 5.79325 8.57045 5.58036C8.33728 5.35734 8.2207 5.08363 8.2207 4.75923C8.2207 4.43483 8.33728 4.16618 8.57045 3.9533C8.80361 3.73027 9.09253 3.61876 9.4372 3.61876C9.78188 3.61876 10.0708 3.7252 10.304 3.93809C10.5371 4.14084 10.6537 4.39935 10.6537 4.71361C10.6537 5.04815 10.5371 5.33199 10.304 5.56516C10.0809 5.78818 9.79201 5.89969 9.4372 5.89969Z" fill="#CBCBCB" />
                        </svg>
                    </div> 
                    <div class="window_info">
                        <p>Базовый вариант исполнения.</p>
                    </div>
                    <div><span>Liner</span></div>
                    <div><span id="base-price">0 ₽</span></div> 
                </div>
                <div class="configurator__option-window configurator__option-window_modified">
                    <div class="info_icon-container">
                        <svg class="info_icon" width="19" height="19" viewBox="0 0 19 19" xmlns="http://www.w3.org/2000/svg">
                            <circle cx="9.29319" cy="9.29319" r="8.79319" fill="white" />
                            <path d="M8.47921 7.23784H10.38L10.304 14.2077H8.40318L8.47921 7.23784ZM9.4372 5.89969C9.09253 5.89969 8.80361 5.79325 8.57045 5.58036C8.33728 5.35734 8.2207 5.08363 8.2207 4.75923C8.2207 4.43483 8.33728 4.16618 8.57045 3.9533C8.80361 3.73027 9.09253 3.61876 9.4372 3.61876C9.78188 3.61876 10.0708 3.7252 10.304 3.93809C10.5371 4.14084 10.6537 4.39935 10.6537 4.71361C10.6537 5.04815 10.5371 5.33199 10.304 5.56516C10.0809 5.78818 9.79201 5.89969 9.4372 5.89969Z" fill="#CBCBCB" />
                        </svg>
                    </div>
                    <div class="window_info">
                        <p>Вариант исполнения с тремя дополнительными защитными слоями (слой прозрачной смолы, декоративны наполнитель, керамика).</p>
                    </div>
                    <div><span>Cristal</span></div>
                    <div><span id="cristal-price"></span></div>
                </div>
            </div>
            <div class="configurator__option equipment_list" data-section="121198">
                <h6 class="configurator__option-header">Опции</h6>
                <div class="configurator__option-grid">
                    <!-- <div class="configurator__option-window">
                        <div class="info_icon-container">
                            <svg class="info_icon" width="19" height="19" viewBox="0 0 19 19" xmlns="http://www.w3.org/2000/svg">
                                <circle cx="9.29319" cy="9.29319" r="8.79319" fill="white" />
                                <path d="M8.47921 7.23784H10.38L10.304 14.2077H8.40318L8.47921 7.23784ZM9.4372 5.89969C9.09253 5.89969 8.80361 5.79325 8.57045 5.58036C8.33728 5.35734 8.2207 5.08363 8.2207 4.75923C8.2207 4.43483 8.33728 4.16618 8.57045 3.9533C8.80361 3.73027 9.09253 3.61876 9.4372 3.61876C9.78188 3.61876 10.0708 3.7252 10.304 3.93809C10.5371 4.14084 10.6537 4.39935 10.6537 4.71361C10.6537 5.04815 10.5371 5.33199 10.304 5.56516C10.0809 5.78818 9.79201 5.89969 9.4372 5.89969Z" fill="#CBCBCB" />
                            </svg>
                        </div>
                        <div class="window_info">
                            <p>Опция HARD-RIB - силовой̆ каркас, интегрированный̆ в чашу бассейна для придания достаточной̆ прочности и удержания воды без внешней̆ обсыпки периметра бассейна.</p>
                        </div>
                        <img src="dist/assets/images/configurator/option_1.png" alt="">
                        <div><span>Система самоочистки</span></div>
                        <div><span>+140 000 ₽</span></div>
                    </div> -->
                    <div class="configurator__option-window" data-window_id="129383">
                        <div class="info_icon-container">
                            <svg class="info_icon" width="19" height="19" viewBox="0 0 19 19" xmlns="http://www.w3.org/2000/svg">
                                <circle cx="9.29319" cy="9.29319" r="8.79319" fill="white" />
                                <path d="M8.47921 7.23784H10.38L10.304 14.2077H8.40318L8.47921 7.23784ZM9.4372 5.89969C9.09253 5.89969 8.80361 5.79325 8.57045 5.58036C8.33728 5.35734 8.2207 5.08363 8.2207 4.75923C8.2207 4.43483 8.33728 4.16618 8.57045 3.9533C8.80361 3.73027 9.09253 3.61876 9.4372 3.61876C9.78188 3.61876 10.0708 3.7252 10.304 3.93809C10.5371 4.14084 10.6537 4.39935 10.6537 4.71361C10.6537 5.04815 10.5371 5.33199 10.304 5.56516C10.0809 5.78818 9.79201 5.89969 9.4372 5.89969Z" fill="#CBCBCB" />
                            </svg>
                        </div>
                        <div class="window_info">
                            <p>Опция HARD-RIB - силовой̆ каркас, интегрированный̆ в чашу бассейна для придания достаточной̆ прочности и удержания воды без внешней̆ обсыпки периметра бассейна.</p>
                        </div>
                        <img src="dist/assets/images/configurator/option_2.png" alt="">
                        <div><span>Самонесущая конструкция</span></div>
                        <div><span class="option_price series__modelPrice"></span></div>
                        <div class="window_icon"><img src="dist/assets/images/configurator/icons/choose.svg" style="width: 360px;max-width: 360px;height: 100%;" alt=""></div>
                    </div>
                    <div class="configurator__option-window">
                        <div class="info_icon-container">
                            <svg class="info_icon" width="19" height="19" viewBox="0 0 19 19" xmlns="http://www.w3.org/2000/svg">
                                <circle cx="9.29319" cy="9.29319" r="8.79319" fill="white" />
                                <path d="M8.47921 7.23784H10.38L10.304 14.2077H8.40318L8.47921 7.23784ZM9.4372 5.89969C9.09253 5.89969 8.80361 5.79325 8.57045 5.58036C8.33728 5.35734 8.2207 5.08363 8.2207 4.75923C8.2207 4.43483 8.33728 4.16618 8.57045 3.9533C8.80361 3.73027 9.09253 3.61876 9.4372 3.61876C9.78188 3.61876 10.0708 3.7252 10.304 3.93809C10.5371 4.14084 10.6537 4.39935 10.6537 4.71361C10.6537 5.04815 10.5371 5.33199 10.304 5.56516C10.0809 5.78818 9.79201 5.89969 9.4372 5.89969Z" fill="#CBCBCB" />
                            </svg>
                        </div>
                        <div class="window_info">
                            <p>Декоративное обрамления чаши бассейна камнем, защищающим также от брызг и выплескивания воды.</p>
                        </div>
                        <img src="dist/assets/images/configurator/option_3.png" alt="">
                        <div><span>Бордюрный камень</span></div>
                    </div>
                    <div class="configurator__option-window">
                        <div class="info_icon-container">
                            <svg class="info_icon" width="19" height="19" viewBox="0 0 19 19" xmlns="http://www.w3.org/2000/svg">
                                <circle cx="9.29319" cy="9.29319" r="8.79319" fill="white" />
                                <path d="M8.47921 7.23784H10.38L10.304 14.2077H8.40318L8.47921 7.23784ZM9.4372 5.89969C9.09253 5.89969 8.80361 5.79325 8.57045 5.58036C8.33728 5.35734 8.2207 5.08363 8.2207 4.75923C8.2207 4.43483 8.33728 4.16618 8.57045 3.9533C8.80361 3.73027 9.09253 3.61876 9.4372 3.61876C9.78188 3.61876 10.0708 3.7252 10.304 3.93809C10.5371 4.14084 10.6537 4.39935 10.6537 4.71361C10.6537 5.04815 10.5371 5.33199 10.304 5.56516C10.0809 5.78818 9.79201 5.89969 9.4372 5.89969Z" fill="#CBCBCB" />
                            </svg>
                        </div>
                        <div class="window_info">
                            <p>Слой полиуретановой пены 3 или 5 см, служит для дополнительного утепления чаши.</p>
                        </div>
                        <img src="dist/assets/images/configurator/option_4.png" alt="">
                        <div><span>Утепление чаши</span></div>
                    </div>
                </div>
            </div>
        </div>
        <div class="configurator__equipment equipment_list" data-section="121199">
            <h5 class="configurator__equipment-title">Основное оборудование</h5>
            <div class="configurator__equipment-grid">
                <?php foreach($json[121199]['groups'] as $key=>$group): ?>
                    <?php if ($key === array_key_last($json[121199]['groups'])) $group['custom_class'] = 'right_hint'; else $group['custom_class'] = '';?>
                    <?=$this->render([$key,$group, $icon = "choose"],'content/pools/configurator/option_window')?>

                <?php endforeach; ?>
            </div>
        </div>
        <div class="configurator__equipment equipment_list" data-section="121200">
            <h5 class="configurator__equipment-title">Дополнительное оборудование</h5>
            <div class="configurator__equipment-grid">
                <?php foreach($json[121200]['groups'] as $key=>$group): ?>
                    <?php if ($key === array_key_last($json[121200]['groups'])) $group['custom_class'] = 'right_hint'; else $group['custom_class'] = '';?>
                    <?=$this->render([$key,$group, $icon = "show"],'content/pools/configurator/option_window')?>
                <?php endforeach; ?>
            </div>
        </div>
        <div class="configurator__equipment" data-section="121201">
            <h5 class="configurator__equipment-title"><?=$json[121201]['name'];?></h5>
            <div class="configurator__equipment-grid">
                <?php foreach($json[121201]['groups'] as $key=>$group): ?>
                    <?php if (count($json[121201]['groups']) > 1 && $key === array_key_last($json[121200]['groups'])) $group['custom_class'] = 'right_hint'; else $group['custom_class'] = '';?>
                    <?=$this->render([$key,$group, $icon = "choose"],'content/pools/configurator/option_window')?>
                <?php endforeach; ?>
            </div>
        </div>
        <div class="configurator__equipment" data-section="121202">
            <h5 class="configurator__equipment-title"><?=$json[121202]['name'];?></h5>
            <div class="configurator__equipment-grid">
                <?php foreach($json[121202]['groups'] as $key=>$group): ?>
                    <?php if (count($json[121202]['groups']) > 1 && $key === array_key_last($json[121202]['groups'])) $group['custom_class'] = 'right_hint'; else $group['custom_class'] = '';?>
                    <?=$this->render([$key,$group, $icon = "choose"],'content/pools/configurator/option_window')?>
                <?php endforeach; ?> 
            </div>
        </div>
        <div class="configurator__equipment" data-section="121205">
            <h5 class="configurator__equipment-title"><?=$json[121205]['name'];?></h5>
            <div class="configurator__equipment-grid">
                <?php foreach($json[121205]['groups'] as $key=>$group): ?>
                    <?php if ($key === array_key_last($json[121205]['groups'])) $group['custom_class'] = 'right_hint'; else $group['custom_class'] = '';?>
                    <?=$this->render([$key,$group, $icon = "choose"],'content/pools/configurator/option_window')?>
                <?php endforeach; ?>
            </div>
        </div>
    </div>
    <div class="configurator__pools configurator__pools--active">
        <h6 class="configurator__option-header">Выберите модель <span style="color: red">*</span></h6>
        <?php foreach($models as $category): ?>
            <?= $this->render($category, 'content/pools/configurator/series_row') ?>
        <?php endforeach; ?>
        
    </div>
</div>
<div class="configurator__estimate">
    <h4>Предварительный расчёт</h4>
    <table class="configurator__estimate-table">
        <tr class="configurator__estimate-tableRow_modified">
            <td>Наименование</td>
            <td>Количество</td>
            <td>Сумма</td>
        </tr>
        <tr>
            <td>Композитный бассейн</td>
            <td>1 шт</td>
            <td>490 000 ₽</td>
        </tr>
        <tr>
            <td>Скиммер ABS пластик (КНР)</td>
            <td>1 шт</td>
            <td>5 000 ₽</td>
        </tr>
        <tr>
            <td>Форсунки ABS пластик (КНР)</td>
            <td>2 шт</td>
            <td>5 000 ₽</td>
        </tr>
        <tr>
            <td>Фильтр D 900 с вентилем</td>
            <td>1 шт</td>
            <td>30 000 ₽</td>
        </tr>
        <tr class="configurator__estimate-tableRow_modified">
            <td>Итого</td>
            <td></td>
            <td>1 384 938 ₽</td>
        </tr>
    </table>
    <div class="configurator__estimate-buttons">
        <button class="configurator__estimate-button">Оставить заявку</button>
        <button class="configurator__estimate-button">Сохранить</button>
    </div>
    <p class="configurator__estimate-message">Внимание! Стоимость строительных и монтажных работ рассчитывается индивидуально после выезда специалиста на объект.</p>
</div>

<div class="configurator__bottom-buttons">
    <div class="center-wrap" >
        <button class="btn-link" type="submit">Сохранить набор</button>
        <div>
            <span id="bottom_price"></span>
            <button class="btn btn--blue showCalc__btn">Показать расчёт</button>
        </div>
    </div>
</div>