<?php
/**
 * Товарное наименование в корзине.
 *
 * @var umiTemplaterPHP|ViewPhpExtension|DemomarketPhpExtension $this
 * @var array $variables
 */

$product = $variables;


?>

<div class="cart__list__item">
    <div class="cart__list__icon">
        <a href="<?= $this->getPath($product['page']) ?>">
        <img class="cart__img" src="<?=$this->thumb($this->getPhotoPath($product['page']),114)[0]?>">
        </a>
        </div>
    <div class="cart__list__text">
        <span class="cart__list__text__name">
            <?= $product['name'] ?>
        </span>
    </div>
    <div class="cart__list__price">
        <span class="cart__list__price__value">
            <?= $this->render($product, 'emarket/cart/product/total_amount') ?>
        </span>
        <span class="cart__list__price__counter" data-id="<?=$product['id']?>" id="order_item_<?=$product['id']?>">
            <img src="resources/img/remove.svg" class="svg cart-counter-icon">
            <span class="cart__list__price__counter_val"><?=$product['amount']?></span>
            <img src="resources/img/add.svg" class="increment_product_quantity svg cart-counter-icon">
        </span>
    </div>
    <div class="cart__list__delete">
        <a class="order_delete" href="#" data-id="<?=$product['id']?>">
        <svg width="15px", height="15px" xmlns="http://www.w3.org/2000/svg" data-name="Layer 1" viewBox="0 0 64 64"><line x1="9.37" x2="54.63" y1="9.37" y2="54.63" fill="none" stroke="#010101" stroke-miterlimit="10" stroke-width="4"/><line x1="9.37" x2="54.63" y1="54.63" y2="9.37" fill="none" stroke="#010101" stroke-miterlimit="10" stroke-width="4"/></svg>
        </a>
    </div>
</div>
<?= $this->render($product['page'], 'emarket/cart/product/suggested_product_list') ?>