<?php
/**
 * Отдельное значение опционного свойства.
 *
 * @var umiTemplaterPHP|ViewPhpExtension|DemomarketPhpExtension $this
 * @var array $variables
 */

list($fieldName, $value) = $variables;
$option = $this->getObjectById(isset($value['rel']) ? $value['rel'] : null);
?>


<?php if ($option): ?>
	<div class="product__power-item" data-name="options[<?= $fieldName ?>]" data-value="<?= $option->getId() ?>" data-price="<?= $this->getFormattedOptionPrice($value) ?>"><?= $this->escape($option->getName()) ?></div>
<?php endif; ?>
