<?php
/**
 * Скелет сайта.
 *
 * @var umiTemplaterPHP|ViewPhpExtension|DemomarketPhpExtension $this
 * @var array $variables
 */

	$p = $variables["page"];
	if ($p AND ($p->getId() == 1351) ) {
		echo $this->render($variables, 'layout/cart');
		exit();
	}
	if ($p AND ($p->getId() == 1352) ) {
		echo $this->render($variables, 'layout/cart_basket_price');
		exit();
	}

	$p = $variables["page"];
	if ($p AND ($p->getId() == 1351)) {
		echo $this->render($variables, 'layout/cart');
		exit();
	}
	if ($_POST["quick_filter"]) {
		$catalog = $this->getCatalog($variables);
		$childs = $this->getChildCategories($variables);
		$childCategoryList = $childs['items'];
		$productList = $this->getPages($catalog);
		
		$pagination = $this->getPagination($catalog);
		$this->setCommonVar('smart_filters', $this->getSmartFilters($variables));
		
		foreach ($productList as $product):
			echo $this->render($product, 'catalog/product/preview/index');
		endforeach;
		
		exit();
	}
	if ($_POST["quick_pagination"]) {
		$catalog = $this->getCatalog($variables);
		$childs = $this->getChildCategories($variables);
		$childCategoryList = $childs['items'];
		$productList = $this->getPages($catalog);
		
		$pagination = $this->getPagination($catalog);
		$this->setCommonVar('smart_filters', $this->getSmartFilters($variables));
		
		echo $this->render($pagination, 'library/pagination');

		exit();
	}

    $cart = $this->getCommonVar('cart');
    $amount = (int) isset($cart['total-amount']) ? $cart['total-amount'] : 0;

    
    $ipAddress = $_SERVER['REMOTE_ADDR'];
    if (array_key_exists('HTTP_X_FORWARDED_FOR', $_SERVER)) {
        $ipAddress = array_pop(explode(',', $_SERVER['HTTP_X_FORWARDED_FOR']));
    }
?>
<!DOCTYPE html>
<html>
	<head>
		<?= $this->render($variables, 'layout/head') ?>
	</head>

	<body data-ip="<?=$ipAddress?>">
        <?php if ($variables['domain-id'] == 2):?>
        <!-- Google Tag Manager (noscript) -->
        <noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-MX3CVSP"
        height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
        <!-- End Google Tag Manager (noscript) -->
        <?php else:?>
        <!-- Google Tag Manager (noscript) -->
        <noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-K9NZCTN"
        height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
        <!-- End Google Tag Manager (noscript) -->
        <?php endif;?>

		<?php if(!empty($variables['pageId']) && $variables['pageId'] == 7762): ?>
			<?= $this->render($variables, $variables['page']->getValue('shablon')) ?>
		<?php else:?>
			<?= $this->render($variables, 'layout/main') ?>
		<?php endif;?>
	

    <script src="https://cdnjs.cloudflare.com/ajax/libs/Swiper/5.4.5/js/swiper.min.js"></script>
    
  <script type="text/javascript" src="dist/js/app.js"></script>
	</body>
</html>
