<?php
/**
 * Опция поля умных фильтров, которое нужно вывести с чекбоксом.
 *
 * @var umiTemplaterPHP|ViewPhpExtension|DemomarketPhpExtension $this
 * @var array $variables
 */

$data = $this->getCheckboxFilterFieldData($variables);
?>

<div class="select__value-selected">
	<input type="checkbox" name="<?= $data['name'] ?>" id="<?= $data['id'] ?>" value="<?= $data['value'] ?>" />
	<label for="<?= $data['id'] ?>">
		<span><?= $data['value'] ?></span>
	</label>
</div>
