<?php
/**
 * Пагинация.
 *
 * @var umiTemplaterPHP|ViewPhpExtension|DemomarketPhpExtension $this
 * @var array $variables
 */

if (!$this->canShowPagination($variables)) {
	return;
}

$pagination = $this->macros('system', 'numpages', [$variables['total'], $variables['per_page']]);
?>

<ul class="pagination_numbers">
	<?= $this->render($pagination, 'blocks/pagination/previous_page') ?>
	<?= $this->render($pagination, 'blocks/pagination/page_list') ?>
	<?= $this->render($pagination, 'blocks/pagination/next_page') ?>
</ul>
 