<header class="header header_1">
  <div class="header__container container">
    <div class="header__logo">
      <a href="#0"><?=$this->render('','svg/logo')?></a>  
    </div>

    <div class="header__left">

    </div>

    <div class="header__phone">
        <a rel="nofollow" href="tel:+70000000010">+7 (000) 000-00-10</a>
        <div class="header__phone_dropdown">
          <div class="wrap">
            <div class="more_phone"><a rel="nofollow" href="tel:+70000000020">+7 (000) 000-00-20<span>Бухгалтерия</span></a></div>
            <div class="more_phone"><a rel="nofollow" href="tel:+70000000030">+7 (000) 000-00-30<span>Отдел продаж</span></a></div>
          </div>
        </div>
        <svg xmlns="http://www.w3.org/2000/svg" width="5" height="3" viewBox="0 0 5 3"><path d="M250,80h5l-2.5,3Z" transform="translate(-250 -80)"></path></svg>
    </div>

    <div class="header__right">

    </div>

    <div class="header__icons">
      <a rel="nofollow" title="Личный кабинет" class="header__user" href="/personal/">
        <svg class="" width="18" height="18" viewBox="0 0 18 18"><path data-name="Ellipse 206 copy 4" d="M909,961a9,9,0,1,1,9-9A9,9,0,0,1,909,961Zm2.571-2.5a6.825,6.825,0,0,0-5.126,0A6.825,6.825,0,0,0,911.571,958.5ZM909,945a6.973,6.973,0,0,0-4.556,12.275,8.787,8.787,0,0,1,9.114,0A6.973,6.973,0,0,0,909,945Zm0,10a4,4,0,1,1,4-4A4,4,0,0,1,909,955Zm0-6a2,2,0,1,0,2,2A2,2,0,0,0,909,949Z" transform="translate(-900 -943)"></path></svg><span class="wrap"><span class="name">Войти</span></span>
      </a>
    </div>
    <button class="btn btn--subtle header__trigger js-header__trigger" aria-label="Toggle menu" aria-expanded="false" aria-controls="header-nav">
      <i class="header__trigger-icon" aria-hidden="true"></i>
      <span>Menu</span>
    </button>
  </div>
  <div class="header__container container max-width-lg">
    <nav class="header__nav js-header__nav" id="header-nav" role="navigation" aria-label="Main">
      <div class="header__nav-inner">
        <div class="header__label">Main menu</div>

          <ul class="header__list" umi:element-id="867" umi:module="content" umi:method="menu">
            <li class="header__item" umi:element-id="867" umi:field-name="name"><a href="#0" class="header__link">Каталог</a></li>
            <li class="header__item"><a href="#0" class="header__link">Акции</a></li>
            <li class="header__item"><a href="#0" class="header__link">Услуги</a></li>
            <li class="header__item"><a href="#0" class="header__link">Блог</a></li>
            <li class="header__item"><a href="#0" class="header__link">Контакты</a></li>
            <li class="header__item header__item--divider" aria-hidden="true"></li>       
          </ul>

      </div> 
    </nav>
  </div>
</header>
 

