<?php
	/**
	 * Блок торговых предложений
	 * @var umiTemplaterPHP|ViewPhpExtension|DemomarketPhpExtension $this
	 * @var array $variables
	 * @var iUmiHierarchyElement $product
	 */
	$product = $variables;
	$characteristicSet = $this->getCharacteristicSet($product->getId());

	

	if (count($characteristicSet) === 0) {
		return;
	}
?>

<div id="price_type_id" data-price-type-id="<?= $this->getPriceTypeId($product->getId()) ?>">
</div>

<div class="product__power additional_options">
	<?php foreach ($characteristicSet as $title => $valueList): ?>
		<div class="additional_options-item <?= $this->getCharacteristicBlockClass($title) ?>" <?=(count($valueList)<2 || $title=='Цена' || $title=='Price')?'style="display:none"':''?>>
			<div class="product__column-title additional_options-text" data-title="<?= $this->escape($title) ?>"><?= $this->escape($title) ?></div>
			<div class="product__power-list additional_options-list" data-title="<?= $this->escape($title) ?>">
				<?php /* foreach ($valueList as $value => $offerIdList): ?>
					<div class="product__power-item" data-offer-id-list="<?= implode(';', $offerIdList) ?>" data-value="<?= $this->escape($value) ?>">
						<?= $this->escape($value) ?>
					</div>
				<?php endforeach; */ ?>
				<select data-characteristic-name="<?= $this->escape($title) ?>" class="<?= $this->getCharacteristicBlockClass($title) ?>" style="display:none">
					<option selected="selected" data-offer-id-list="" data-value="">
						<?= $this->translate('js-not-selected') ?>
					</option>
					<?php foreach ($valueList as $value => $offerIdList): ?>
						<option data-offer-id-list="<?= implode(';', $offerIdList) ?>" data-value="<?= $this->escape($value) ?>">
							<?= $this->escape($value) ?>
						</option>
					<?php endforeach; ?>
				</select>
			</div>
		</div>
	<?php endforeach; ?>
</div>

