<?php
/**
 * Форма поиска в шапке сайта.
 * За функционал поиска отвечает скрипт js/search.js.
 *
 * @var umiTemplaterPHP|ViewPhpExtension|DemomarketPhpExtension $this
 * @var array $variables
 */

$action = $this->getCommonVar('pre_lang') . '/search/search_do/';
?>
<div class="header__form">
    <form class="search" action="<?= $action ?>" id="searchForm">
    <input class="search__input" type="search" name="search_string"	autocomplete="off" class="tooltip_toggle" placeholder="Я ищу ...">
    <button class="btn btn--blue search__btn" type="submit">Найти</button>
    </form>
    <script id="search_result_template" type="text/template">
        <% _.each(typesList, function(type) { %>
            <ul class="goods_list">
                <li>
                    <span class="list_heading gray_text">
                        <%= type.module ? type.module : '&nbsp;' %>
                    </span>

                    <ul>
                        <% _.each(type.elements, function(page) { %>
                            <li class="clearfix">
                                <a href="<%= page.link %>" class="pull-left">
                                    <%= page.context %>
                                </a>
                            </li>
                        <% }); %>
                    </ul>
                </li>
            </ul>
        <% }); %>

        <div class="all_result">
            <a><?= $this->translate('show_all_search_results') ?></a>
        </div>
    </script>
</div>

<style>


	@media screen and (max-width: 768px){
		.search_content{
			display:none;
		}
		main .search_results .grey_border{
			padding: 10px 15px;
		}
	}
#searchForm input.tooltip_toggle{
	width: 100%;
    margin-top: 13px;
    background: #f3f5f7;
    padding-left: 37px;
    cursor: text;
    border-radius: 100px 0 0 100px;
}
.search_content {
    position: absolute;
    z-index: 1000;
    background: #fff;
    width: auto;
    padding: 18px 20px;
    font-size: 18px;
    box-shadow: 0px 7px 30px rgba(204, 204, 204, 0.54);
}
a.pull-left {
    font-size: 15px;
}
ul.goods_list {
    max-width: 700px;
}

.search-icon {
  -webkit-mask-image:
      url(data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIyNCIgaGVpZ2h0PSIyNCIgZmlsbD0iIzVGNjM2OCI+PHBhdGggZD0iTTE1LjUgMTRoLS43OWwtLjI4LS4yN0E2LjQ3MSA2LjQ3MSAwIDAgMCAxNiA5LjUgNi41IDYuNSAwIDEgMCA5LjUgMTZjMS42MSAwIDMuMDktLjU5IDQuMjMtMS41N2wuMjcuMjh2Ljc5bDUgNC45OUwyMC40OSAxOWwtNC45OS01em0tNiAwQzcuMDEgMTQgNSAxMS45OSA1IDkuNVM3LjAxIDUgOS41IDUgMTQgNy4wMSAxNCA5LjUgMTEuOTkgMTQgOS41IDE0eiIvPjwvc3ZnPg==);
  -webkit-mask-size: 20px;
}
.clock-icon, .search-icon {
	-webkit-mask-position: center;
    -webkit-mask-repeat: no-repeat;
    background-color: #757575;
    bottom: 0;
    left: 10px;
    position: absolute;
    top: 14px;
    width: 24px;
}
</style>
