<?php
$p = $variables['page'];
$pic = $p->getValue('header_pic');
$header = $this->escape($variables['header']);
$fon_temnyj = $p->getValue('fon_temnyj');
?>



<?php if(!$p->getValue('zagolovok_na_kartinke')): ?>
    <div class="pool-filters__title"><?=$header?></div>
<?php endif; ?>
<?= $this->render($variables, 'layout/header/breadcrumbs') ?>

<?php if($pic): $pic = $this->thumb($pic,1200,'auto'); ?>
    <?php if($p->getValue('zagolovok_na_kartinke')): ?>
        <section class="blog-header <?=($fon_temnyj)?'blog-header--dark':''?>" data-bgimage="<?=$pic[0]?>"> 
            <h2 class="blog-header__title"><?=$header?></h2>
            <div class="blog-header__paragraph"><?=$p->getValue('anons')?></div>
        </section>
    <?php else: ?>
    <img class="blog-header__img" src="<?=$pic[0]?>">
    <?php endif; ?>
<?php endif; ?>

