<?php
/**
 * Страница с результатами поиска.
 *
 * @var umiTemplaterPHP|ViewPhpExtension|DemomarketPhpExtension $this
 * @var array $variables
 */

$data = $this->getSearchResult();


?>


<div class="center-wrap" style="padding-top: 2.1rem;">
<div class="pool-filters__title"><?= str_replace(['страниц'],['товаров'],$this->getSearchResultHeader($data)) ?></div>
</div>

<main class="center-wrap " style="padding-top: 2.1rem;">

        <section class="pool-filters">
          <div class="center-wrap">

				<?php if (umiCount($data['lines']) > 0): ?>
					<?= $this->render($data, "search/result") ?>
				<?php endif; ?>
    
          </div>
		</section>

</main>