<?php
/**
 * Страница с результатами поиска.
 *
 * @var umiTemplaterPHP|ViewPhpExtension|DemomarketPhpExtension $this
 * @var array $variables
 */

$data = $this->getSearchResult();
$dataProducts = $this->getSearchResultProducts();
?>


<div class="center-wrap pt-2">
<div class="pool-filters__title">Найдено <?=umiCount($dataProducts['lines'])?> товаров и <?=umiCount($data['lines'])?> страниц</div>
</div>

<main class="center-wrap pt-2">

        <section class="pool-filters">


				<?php if (umiCount($data['lines']) > 0 || umiCount($dataProducts['lines']) > 0): ?>
					<?= $this->render([$data,$dataProducts], "search/result") ?>
				<?php endif; ?>
    

		</section>

</main>