<?php
/**
 * Изображение превью товара.
 *
 * @var umiTemplaterPHP|ViewPhpExtension|DemomarketPhpExtension $this
 * @var iUmiHierarchyElement $variables
 */

$product = $variables;
?>

<a href="<?= $this->getPath($product) ?>">
	<div class="item_img">
		<div class="label_new"><?= $this->translate('label_new') ?></div>

		<img src="<?=$this->thumb($this->getPhotoPath($product),'auto',150)[0]?>">

	</div>
</a>
