<?php 
$page = $variables['page'];
$catalog = $this->getProductsListFromCategory($variables['pageId'],100);

?>
<div class="center-wrap" style="padding-top: 2.1rem;">
    <?= $this->render($variables, 'layout/header/titleWithBread') ?>
</div>
 

    <div class="catalog-list" >
        <?php foreach($catalog['items'] as $category): ?>
        <?= $this->render($category, 'content/services/preview') ?>
        <?php endforeach; ?>
    </div>

<div class="center-wrap" style="padding-top: 2.1rem;">
    <div class="article" style="padding-top: 2.1rem;">
        <?=$page->getValue('content')?>
    </div>
</div>
  