<?php 
$page = $variables['page'];
$catalog = $this->getProductsListFromCategory($variables['pageId'],100);

?>
<div class="center-wrap pt-2">
    <?= $this->render($variables, 'layout/header/titleWithBread') ?>
</div>
 

    <div class="catalog-list" >
        <?php foreach($catalog['items'] as $category): ?>
        <?= $this->render($category, 'content/services/preview') ?>
        <?php endforeach; ?>
    </div>

<div class="center-wrap pt-2">
    <div class="article pt-2">
        <?=$page->getValue('content')?>
    </div>
</div>
  