<?php
/**
 * Пустая корзина.
 *
 * @var umiTemplaterPHP|ViewPhpExtension|DemomarketPhpExtension $this
 * @var array $variables
 */
?>

<div class="cart-empty">
	<div class="cart-empty_container">
		<div class="cart-empty_image desktop--hide">
			<img src="./src/assets/images/empty_cart.png" alt="">
		</div>
		<div class="cart-empty_content">
			<h3>В корзине пока ничего нет</h3>
			<p>
			Начните с главной страницы или воспользуйтесь поиском, чтобы найти что-то конкретное
			</p>
			<a href="/" class="cart-empty_goHome btn btn--blue">Перейти на главную</a>
		</div>
		<div class="cart-empty_image mobile--hide">
			<img src="./src/assets/images/empty_cart.png" alt="">
		</div>
	</div>
</div>
