<?php
/**
 * Любой способ доставки, кроме ApiShip.
 *
 * @var umiTemplaterPHP|ViewPhpExtension|DemomarketPhpExtension $this
 * @var array $variables
 */

$delivery = $variables;
$umiObjects = umiObjectsCollection::getInstance();
$relationId = $delivery['id'];



	$relation = $umiObjects->getObject($relationId);

	if ($relation instanceof iUmiObject) {
		$value = $relation->getValue('description');
	}
?>

<div class="data-form__wrapper">
	<label class="data-form__label">
		<input
			type="radio"
			name="delivery-id"
			value="<?= $delivery['id'] ?>"
            class="data-form__input_type_radio"
			data-price="<?=$relation->getValue('price')?>"
			required
			<?= $this->getRadioStatusByActivity($delivery) ?>
		/>
        <span class="checkmark"></span>
		<span><?= $this->escape($delivery['name']) ?></span>

		<p class="data-form__input__desc">  
		<?= $this->escape($value) ?>
			 
		</p>
	</label>
</div>
