<div class="simple-title articles__title">Базовые цвета</div>
<div style="" class="product__colors product__colors--col3">
<svg width="388" viewBox="0 0 388 375" fill="none" xmlns="http://www.w3.org/2000/svg">
    <rect width="387.253" height="374.98" fill="#ECEAEA"/>
</svg>
<svg width="388" viewBox="0 0 388 375" fill="none" xmlns="http://www.w3.org/2000/svg">
    <rect width="387.253" height="374.98" fill="#79C2EC"/>
</svg>
</div>
<div class="simple-title articles__title" style="padding-top: 2.1rem;">Цвета GRANI CRISTAL</div>
<div class="article" style="margin:0;">
    <p>Подробнее о варианте исполнения CRISTAL вы можете узнать на владке "Описание".</p>
</div>
<div style="" class="product__colors product__colors--col3">
    <a href="/images/content/abpool/color/12_ms-42.png" data-fancybox="grani"><img src="/images/content/abpool/color/12_ms-42.png"></a>
    <a href="/images/content/abpool/color/12_ms-43_1.png" data-fancybox="grani"><img src="/images/content/abpool/color/12_ms-43_1.png"></a>
    <a href="/images/content/abpool/color/12_ms-43.png" data-fancybox="grani"><img src="/images/content/abpool/color/12_ms-43.png"></a>
    <a href="/images/content/abpool/color/12_ms-43_2.png" data-fancybox="grani"><img src="/images/content/abpool/color/12_ms-43_2.png"></a>
    <a href="/images/content/abpool/color/12_ms-43_4.png" data-fancybox="grani"><img src="/images/content/abpool/color/12_ms-43_4.png"></a>
    <a href="/images/content/abpool/color/12_ms-43_3.png" data-fancybox="grani"><img src="/images/content/abpool/color/12_ms-43_3.png"></a>
    <a href="/images/content/abpool/color/12_ms-43_6.png" data-fancybox="grani"><img src="/images/content/abpool/color/12_ms-43_6.png"></a>
    <a href="/images/content/abpool/color/12_ms-43_5.png" data-fancybox="grani"><img src="/images/content/abpool/color/12_ms-43_5.png"></a>
    <a href="/images/content/abpool/color/12_ms-43_7.png" data-fancybox="grani"><img src="/images/content/abpool/color/12_ms-43_7.png"></a>
    
</div>


<style>
.product__colors{
    display:flex;
    flex-wrap: wrap;
}

.product__colors img,.product__colors svg{
}

.product__colors.product__colors--col3 a,.product__colors.product__colors--col3 svg{
    max-width: 33%;
    padding: 30px;
}

@media screen and (max-width:768px){
    .product__colors.product__colors--col3 a,.product__colors.product__colors--col3 svg{
        padding: 6px;
    }

}

</style>