<?php
/**
 * Статический блок с товарами в корзине (не поддерживается изменение содержимого корзины).
 *
 * @var umiTemplaterPHP|ViewPhpExtension|DemomarketPhpExtension $this
 * @var array $variables
 */

$cart = $this->macros('emarket', 'cart');
$productList = $this->getOrderItems($cart);
$cart['drawFormButton'] = true;
?>

<div class="cart onestep mobile--hide">
	<div data-full-cartlist="hide" class="cart__hide-list d-sm-none hidden_tablet">
		<a href="javascript:;" class="cart__hide-list-trigger">
			Скрыть детали заказа
			<img src="/templates/axlab_2018/images/icons/small-blue-chevron.svg" alt="">
		</a>
	</div>
	<div class="">
		<h2 class="data-form__title pt-0">
			<?= $this->translate('cart_reminder') ?>
		</h2>
	</div>
	<?= $this->render($cart, 'emarket/cart/product_list') ?>
</div>

<div class="cart onestep-mobile hidden desktop--hide">
	<?= $this->render($cart, 'emarket/cart/product_list') ?>
</div>