<?php
/**
 * Выбор способа доставки при оформлении заказа в один шаг.
 *
 * @var umiTemplaterPHP|ViewPhpExtension|DemomarketPhpExtension $this
 * @var array $variables
 */

$deliveryList = isset($variables['onestep']['delivery_choose']) ? $variables['onestep']['delivery_choose'] : [];
?>

<?php if ($deliveryList): ?>
	<div class="delivery_choose onestep del_row order_img_1">
		<div class="del_content">
			<span class="data-form__title">
				<?= $this->translate('delivery_agent') ?>
			</span>

			<?= $this->render($deliveryList, 'emarket/delivery/choose/list') ?>
		</div>
	</div>
<?php endif; ?>
