<?php
/**
 * Поле умных фильтров, которое нужно вывести с радиокнопками.
 *
 * @var umiTemplaterPHP|ViewPhpExtension|DemomarketPhpExtension $this
 * @var array $variables
 */

$fieldTitle = $this->getFilterFieldAttribute($variables, 'title');
$fieldName = $this->getFilterFieldAttribute($variables, 'name');
$selected = $this->getChecked($variables);
?>

<div class="select">
	<div class="select__value">
	<div><?= $fieldTitle ?></div>
	</div>
	<svg class="select__arrow" width="6" height="4" viewBox="0 0 6 4" fill="none" xmlns="http://www.w3.org/2000/svg">
	<path d="M2.86243 4L0.643236 0.25L5.08162 0.25L2.86243 4Z"></path>
	</svg>
	<div class="select__variants">
		<div class="check_container">
			<div>
				<label>
					<input type="radio" name="filter[<?= $fieldName ?>]" value="1" <?= $selected[1] ?> />
					<span></span><?= $this->translate('boolean_yes') ?>
				</label>
			</div>

			<div>
				<label>
					<input type="radio" name="filter[<?= $fieldName ?>]" value="0" <?= $selected[0] ?> />
					<span></span><?= $this->translate('boolean_no') ?>
				</label>
			</div>

			<div>
				<label>
					<input type="radio" name="filter[<?= $fieldName ?>]" value="" <?= $selected[2] ?> />
					<span></span><?= $this->translate('boolean_both') ?>
				</label>
			</div>
		</div>
	</div>
</div>