<div class="building-slider">
    <div class="swiper-container">
      <div class="swiper-wrapper">
        <div class="swiper-slide"><img class="building-pools__img" src="dist/assets/images/main-screen__img.png" alt="">
          <div class="center-wrap"><img class="building-slider__img mobile--hide" src="dist/assets/images/main-screen__img.png" alt=""><img class="building-slider__img desktop--hide" src="dist/assets/images/main-screen__img.png" alt="">
            <div class="building-slider__content">
              <div class="building-slider__title">Строительство бассейнов</div>
              <div class="building-slider__subtitle">Спроектируем в 3D и построим ваш бассейн в любом регионе России</div>
              <div class="btn">Подробнее</div>
            </div>
          </div>
        </div>
        <div class="swiper-slide"><img class="building-pools__img" src="dist/assets/images/building-slider__img1.png" alt="">
          <div class="center-wrap"><img class="building-slider__img mobile--hide" src="dist/assets/images/building-slider__img1.png" alt=""><img class="building-slider__img desktop--hide" src="dist/assets/images/building-slider__img1--mobile.png" alt="">
            <div class="building-slider__content">
              <div class="building-slider__title">Строительство бассейнов</div>
              <div class="building-slider__subtitle">Спроектируем в 3D и построим ваш бассейн в любом регионе России</div>
              <div class="btn">Подробнее</div>
            </div>
          </div>
        </div>
        <div class="swiper-slide"><img class="building-pools__img" src="dist/assets/images/main-screen__img.png" alt="">
          <div class="center-wrap"><img class="building-slider__img mobile--hide" src="dist/assets/images/main-screen__img.png" alt=""><img class="building-slider__img desktop--hide" src="dist/assets/images/main-screen__img.png" alt="">
            <div class="building-slider__content">
              <div class="building-slider__title">Строительство бассейнов</div>
              <div class="building-slider__subtitle">Спроектируем в 3D и построим ваш бассейн в любом регионе России</div>
              <div class="btn">Подробнее</div>
            </div>
          </div>
        </div>
        <div class="swiper-slide"><img class="building-pools__img" src="dist/assets/images/building-slider__img1.png" alt="">
          <div class="center-wrap"><img class="building-slider__img mobile--hide" src="dist/assets/images/building-slider__img1.png" alt=""><img class="building-slider__img desktop--hide" src="dist/assets/images/building-slider__img1--mobile.png" alt="">
            <div class="building-slider__content">
              <div class="building-slider__title">Строительство бассейнов</div>
              <div class="building-slider__subtitle">Спроектируем в 3D и построим ваш бассейн в любом регионе России</div>
              <div class="btn">Подробнее</div>
            </div>
          </div>
        </div>
        <div class="swiper-slide"><img class="building-pools__img" src="dist/assets/images/building-slider__img1.png" alt="">
          <div class="center-wrap"><img class="building-slider__img mobile--hide" src="dist/assets/images/building-slider__img1.png" alt=""><img class="building-slider__img desktop--hide" src="dist/assets/images/building-slider__img1--mobile.png" alt="">
            <div class="building-slider__content">
              <div class="building-slider__title">Строительство бассейнов</div>
              <div class="building-slider__subtitle">Спроектируем в 3D и построим ваш бассейн в любом регионе России</div>
              <div class="btn">Подробнее</div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="center-wrap">
      <div class="swiper-pagination"></div>
    </div>
  </div>