<?php
$orderForm = $this->macros('emarket', 'createForm', ['emarket-purchase-oneclick']);
?>
<form class="inputs" action="" onsubmit="ym(80112226,'reachGoal','one_click_send')">
    <div id="one_click_order_optioned_properties">
        <!-- Сюда будут динамически подставлены опционные свойства конкретного товара
                при нажатии на кнопку "Купить в один клик", если у товара есть такие свойства. -->
    </div>
    
    <?php foreach ($orderForm['groups'] as $group): ?>
        <div class="inputs__row">
        <?php foreach ($group['fields'] as $field): ?>
                <?= $this->render($field, "data/form_field/{$field['type']}") ?>
        <?php endforeach; ?>
        </div>
    <?php endforeach; ?>
    
    <div class="inputs__row">
    <div class="inputs__field-wrap">
        <input class="btn btn--black" type="submit" value="Отправить заявку">
    </div>
    <div class="inputs__field-wrap mobile--hide">
        <div class="inputs__personal">
        <p>Нажимая на кнопку “Отправить заявку”, я соглашаюст с условиями на передачу</p><a class="inputs__personal-link" href="">персональных данных</a>
        </div>
    </div>
    </div>
</form>  