<section class="contact" id="contact"><img class="contact__img" src="dist/assets/images/contact__img.png" alt="">
  <div class="center-wrap">
    <div class="contact__wrap">
      <div class="contact__form">
        <div class="contact__title">Получите помощь специалиста</div>
        <form class="inputs" action="" style="font-size: 1.2rem;">
          <div class="inputs__row">
            <div class="inputs__field-wrap">
              <input class="inputs__field" type="text" name="data[new][name]" required="" minlength="2">
              <label class="inputs__label" for="text"><span class="inputs__content">Имя</span></label>
            </div>
            <div class="inputs__field-wrap">
              <input class="inputs__field" type="tel" name="data[new][phone]" required="">
              <label class="inputs__label" for="phone"><span class="inputs__content inputs__content--required">Телефон</span></label>
            </div>
          </div>
          <div class="inputs__row">
            <div class="inputs__field-wrap">
              <input class="btn btn--black" type="submit" value="Отправить заявку">
              <input type="hidden" name="system_form_id" value="232">
              <input type="hidden" name="system_email_to" value="959">
            </div>
            <div class="inputs__field-wrap mobile--hide">
              <div class="inputs__personal">
                <p>Нажимая на кнопку “Отправить заявку”, я соглашаюст с условиями на передачу</p><a class="inputs__personal-link" href="">персональных данных</a>
              </div>
            </div>

            

          </div>
        </form>
      </div>
      <!--div class="contact__constructor mobile--hide">
        <div class="contact__title contact__title--constructor">Посетите конструктор  </div>
        <div class="contact__text">
          <p>Соберите свой бассейн онлайн<br> и получите коммерческое предложение</p>
        </div>
        <div class="btn">Приступить</div>
      </div-->
    </div> 
  </div>
</section>