<?php
$page = $variables['page'];
?>
<div class="right-slide__block pool">
<?= $this->render($variables, 'layout/header/breadcrumbs') ?>
    <span class="right-slide__title"><?= $this->escape($variables['header']) ?></span>

<section style="margin-bottom:80px">
    <div style="
    text-align: center;
    padding-bottom: 35px;
">
        <span style="
    font-size: 30px;
">Тип будущего бассейна</span>
    </div>
    <div style="
    display: flex;
    justify-content: center;
">
        <div style="text-align: center;padding: 0 30px;max-width: 450px;">
            <img src="https://tvoybasseyn.ru/wp-content/uploads/2017/05/perelivnoy.png" style="
    padding-bottom: 10px;
">
            <span style="
    display: block;
    font-size: 21px;
">Переливной бассейн</span>
            <span>Уровень зеркала воды в таком бассейне равен босоножной зоне в горизонте.</span>
        </div>
        <div style="
    text-align: center;
    padding: 0 30px;
    max-width: 450px;
">
            <img src="https://tvoybasseyn.ru/wp-content/uploads/2017/05/skimmerny.png" style="
    padding-bottom: 10px;
">
            <span style="
    display: block;
    font-size: 21px;
">Скиммерный бассейн</span>
            <span>Верхний (самый загрязненный) слой воды забирается с помощью специального устройства — скиммера.</span>
        </div>
    </div>
</section>

<section style="margin-bottom:80px;padding:80px 0;background-color:#335d93">
    <div style="
    text-align: center;
    padding-bottom: 35px;
">
        <span style="
    font-size: 30px;color:#fff;
">Проектирование</span>
</div>
 
    <div style="color:#fff;display: flex;justify-content: space-around;">
        <div style="
    text-align: center;
    max-width: 25%;
    padding: 0 20px;
">
            <img src="https://tvoybasseyn.ru/wp-content/uploads/2017/05/mark.png">
            <span style="
    display: block;
    padding-top: 15px;    font-size: 21px;
">Что и где строим?</span>
        </div>
        <div style="
    max-width: 25%;
    text-align: center;
    padding: 0 20px;
">
            <img src="https://tvoybasseyn.ru/wp-content/uploads/2017/05/trngl.png">
            <span style="
    display: block;
    padding-top: 15px;    font-size: 21px;
">Размеры</span>
        </div>
        <div style="
    max-width: 25%;
    padding: 0 20px;
    text-align: center;
">
            <img src="https://tvoybasseyn.ru/wp-content/uploads/2017/05/worker.png">
            <span style="
    display: block;
    padding-top: 15px;    font-size: 21px;
">Выезд специалистов</span>
        </div>
        <div style="
    max-width: 25%;
    padding: 0 20px;
    text-align: center;
">
            <img src="https://tvoybasseyn.ru/wp-content/uploads/2017/05/compass.png">
            <span style="
    display: block;
    padding-top: 15px;    font-size: 21px;
">Геодезическая разведка на грунт и нагрузки</span>
        </div>
    </div>
    </section>

    <section style="padding-bottom:80px;">
    <div style="
    text-align: center;
    padding-bottom: 35px;
">
        <span style="
    font-size: 30px;
">Подбор оборудования</span>
</div>

<div style="display: flex;    justify-content: space-evenly;
    flex-wrap: wrap;">
<div style="
    padding: 0 20px;
    text-align: center;
    width: 25%;
    margin-bottom: 30px;
">
<img src="https://tvoybasseyn.ru/wp-content/uploads/2017/05/forsunki.png" alt="" style="
    padding-bottom: 15px;
    max-width: 200px;
">
<span style="
    display: block;
    font-size: 21px;
">Форсунки</span>
</div>
<div style="
    padding: 0 20px;
    text-align: center;
    width: 25%;
    margin-bottom: 30px;
">
<img src="https://tvoybasseyn.ru/wp-content/uploads/2017/05/skimmery.png" alt="" style="
    padding-bottom: 15px;
    max-width: 200px;
">
<span style="
    display: block;
    font-size: 21px;
">Скиммеры</span>
</div>
<div style="
    padding: 0 20px;
    text-align: center;
    width: 25%;
    margin-bottom: 30px;
">
<img src="https://tvoybasseyn.ru/wp-content/uploads/2017/05/dop-osves.png" alt="" style="
    padding-bottom: 15px;
    max-width: 200px;
">
<span style="
    display: block;
    font-size: 21px;
">Дополнительное освещение</span>
</div>
<div style="
    padding: 0 20px;
    text-align: center;
    width: 25%;
    margin-bottom: 30px;
">
<img src="https://tvoybasseyn.ru/wp-content/uploads/2017/05/geyzery.png" alt="" style="
    padding-bottom: 15px;
    max-width: 200px;
">
<span style="
    display: block;
    font-size: 21px;
">Гейзеры</span>
</div>
<div style="
    padding: 0 20px;
    text-align: center;
    width: 25%;
    margin-bottom: 30px;
">
<img src="https://tvoybasseyn.ru/wp-content/uploads/2017/05/vodopady.png" alt="" style="
    padding-bottom: 15px;
    max-width: 200px;
">
<span style="
    display: block;
    font-size: 21px;
">Водопады</span>
</div>
<div style="
    padding: 0 20px;
    text-align: center;
    width: 25%;
    margin-bottom: 30px;
">
<img src="https://tvoybasseyn.ru/wp-content/uploads/2017/05/gidromassaj.png" alt="" style="
    padding-bottom: 15px;
    max-width: 200px;
">
<span style="
    display: block;
    font-size: 21px;
">Гидромассаж</span>
</div>
<div style="
    padding: 0 20px;
    text-align: center;
    width: 25%;
    margin-bottom: 30px;
">
<img src="https://tvoybasseyn.ru/wp-content/uploads/2017/05/protivotok.png" alt="" style="
    padding-bottom: 15px;
    max-width: 200px;
">
<span style="
    display: block;
    font-size: 21px;
">Противоток</span>
</div>


</div>
    </section>

</div>

<div class="right-slide__block">
  <div class="article">
    <?=$page->getValue('content')?>
  </div>
</div>