<?php
    $settings = $this->getSettingsContainer();
    $page = $variables['page'];
    $catalog = $this->getProductsListFromCategory($variables['pageId'],100);
    $projects = $this->getProjects($page->id); 
?>
<div class="right-slide__block">
    <div class="fixedSubmenu fixedSubmenu__fixed">
        <div class="fixedSubmenu__item fixedSubmenu__item_active" data-url="#desc">Описание</div>
<?php if($projects){ ?><div class="fixedSubmenu__item" data-url="#portfolio">Реализованные проекты</div><?php } ?>
        <!--div-- class="fixedSubmenu__item">Рассчитать стоимость</!--div-->
<?php if($page->getValue('setup')) { ?><div class="fixedSubmenu__item" data-url="#setup">Установка и обслуживание</div><?php } ?>
<?php if($page->getValue('catalog')) { ?><div class="fixedSubmenu__item" data-url="#catalog">Приобрести</div><?php } ?>
    </div>

    <?= $this->render($variables, 'layout/header/breadcrumbs') ?>
 
    <span class="right-slide__title"><?= $this->escape($variables['header']) ?></span>

    

    <div class="article" id="desc">
        <?=$page->getValue('content')?>
    </div>
</div>


<?php
   if($projects){ 
?>
<div id="portfolio"> 
    <h2 class="right-slide__blockH2">Готовые проекты</h2>
    <div class="right-slide__block">
        <div class="gallery swiper-container pool__relised">
            <div class="swiper-wrapper">
                <?= $this->render($projects, 'content/gallery/gallery_list')?>
            </div>
            <div class="swiper-button-next swiper-button-black"></div>
            <div class="swiper-button-prev swiper-button-black"></div>
        </div>
    </div>
</div>
<?php } ?>

<?php if($page->getValue('setup')) { ?>
<div class="right-slide__block">
<div class="article" id="setup">
    <h2 class="right-slide__blockH2">Установка бассейна</h2>
        <?=$page->getValue('setup')?>
    </div>
</div>
<?php } ?>

<?php if($page->getValue('catalog_url')){ ?>
<div class="right-slide__block">
    <div id="catalog" class="article">
            <h2 class="right-slide__blockH2">Купить бассейн</h2>
            <?=$page->getValue('catalog')?>
           
            <a class="btn" target="_blank" href="/shop/sbornye-bassejny/">Перейти в Интернет-магазин</a>
    </div>
</div>
<?php } ?>




<style>

    .breadCrumbs {
        padding-top: 54px;
    }
    ol li{
        list-style-type: decimal-leading-zero;
        margin-left: 27px;
    }

    .form-field__wrapper{
        display:initial;
    }

    table{
        width: 100%;
    }

    table tr:nth-child(odd), .row.gray, .tabs-navigation.small.gray li a {
        background: #F5F5F5;
    }

    table td,table th {
    font-family:Arial;
    font-size:14px;
    line-height:18px;
    border-left:1px solid #E2E6E7;
    padding:15px 30px;
    }

    table td.price {
    color:#0C7DC3;
    font-size:16px;
    font-weight:700;
    }

    table td:first-child,table th:first-child {
    border-left:none;
    }

    .radius {
    border-radius:50%;
    -moz-border-radius:50%;
    -webkit-border-radius:50%;
    }
</style>