<?php 

$page = $variables['page'];
$main_photo = '';
$photos = $page->getValue('photos');
if($photos) $main_photo = $photos[0]->getFilePath(1);
$price = 0;
if($page->getValue('stoimost')) $price = str_replace(' ','',$page->getValue('stoimost'));
$price = number_format($price, 0, ',', ' ');

$settings = $this->getSettingsContainer();
$objId = $settings->getValue('uslugi_v_tovare');
$uslugi = umiObjectsCollection::getInstance()->getGuidedItems($objId);

$props = [];
if($p=$page->getValue('dlina')) $props['Длина'] = $p.' м';
if($p=$page->getValue('shirina')) $props['Ширина'] = $p.' м';
if($p=$page->getValue('glubina')) $props['Глубина'] = $p.' м';
if($p=$page->getValue('vysoty')) $props['Выс'] = $p.' м';
if($p=$page->getValue('obem')) $props['Объем'] = $p.' м<sup>3</sup>';
if($p=$page->getValue('kolichestvo_segmentov')) $props['Сегм'] = $p.' шт';

?>
<div class="center-wrap pt-2 pool">
<?= $this->render($variables, 'layout/header/breadcrumbs') ?>
    <div class="product__title"><?= $this->escape($variables['header']) ?></div>

    <div class="pool__wrapper">
        <div class="pool__leftCol pool__leftCol_gidro">
            <?php if(count($photos) > 1):?>
                <div class="swiper-container pool__slider" style="    min-width: 100%;">
                <div class="swiper-wrapper">
                    <?php foreach($photos as $photo): ?>
                        <div class="swiper-slide">
                            <img src="<?=$photo->getFilePath(1)?>" class="swiper-lazy" style="object-fit: contain;height:100%">
                            <div class="swiper-lazy-preloader swiper-lazy-preloader-white"></div>
                        </div>
                    <?php endforeach; ?>    
                </div>
                <div class="swiper-button-next swiper-button-black"></div>
                <div class="swiper-button-prev swiper-button-black"></div>

                </div>
            <?php else:?>
                <div class="gidro_img">
                    <img src="<?=$main_photo?>" alt="">
                </div>
            <?php endif;?>
            <div class="pool__props">
            <?php foreach($props as $k=>$prop): ?>
                    <div class="pool__prop">
                        <span class="pool__propTitle"><?=$k?></span>
                        <span class="pool__propVal"><?=$prop?></span>
                    </div>
            <?php endforeach; ?>
              
            </div>
            <?php if($cher = $page->getValue('chertezh')){?><a data-fancybox href="<?=$cher->getFilePath(1)?>" class="pool__download"><?php $style='margin-right:10px;';$svg='pdf';include 'blocks/svg.php'?>
            СКАЧАТЬ ЧЕРТЕЖ</a><?php } ?>

           
        </div>
        <div class="pool__rightCol">
            <div class="pool__constructor" style="display:none">
                <img src="resources/img/constructor.png">
            </div>




            <div class="pool__rightCol">
                

                <video class="wp-video-shortcode lazy-hidden mrSpa_video" muted id="video-33421-1_html5" width="640" height="360" loop="1" autoplay="1" preload="metadata" src="resources/mrSpa.mp4" style="width: 100%;height: auto;"><source type="video/mp4" src="resources/mrSpa.mp4"><a href="resources/mrSpa.mp4">mrSpa.mp4</a></video>


                <div class="pool__filter">
                        
                        <div class="filter">
                            <div class="filter__block">
                                <div class="filter__field filter__field_active">Simple</div>
                                <div class="filter__field">Classik</div>
                                <div class="filter__field">Avangard</div>
                            </div>
                        </div>
                    </div>



                    <div class="pool__summaryLine pool__summaryLine_total"><span class="pool__summaryTitle">Стоимость</span><span class="pool__summarySumm"><?=$price?> ₽</span></div>
                    <div class="pool__summaryAction"><a class="btn btn--primary" onclick="$('#callback input[name=&quot;system_form_id&quot;]').val(236);$('#callback .popup-form__title').text('Консультация по бассейну <?=$page->name?>');show_popup('callback')">Консультация</a></div>
                    
                
                
            </div>

            <?= $this->render(['name'=>'Заказать консультацию','title'=>'Консультация по по бассейну '.$page->name,'ym'=>'consultation'], 'blocks/forms/callback') ?>





        </div>
    </div>


</div>
<?php if($page->getValue('cveta')){ $list = umiObjectsCollection::getInstance()->getGuidedItems($page->getValue('cveta'));$cveta = $this->vsk_objById(array_keys($list));  ?>
<div class="gidro__colors center-wrap pt-2">
    <h2>Цвета</h2>
    <div style="display: flex;flex-wrap: wrap;">
    <?php foreach($cveta as $item): ?>
        <div style="flex: 0 0 25%;max-width: 25%;text-align: center;padding: 10px;">
            <img data-fancybox="galera" data-src="<?=$item->getValue('photo')?>" src="<?=$item->getValue('photo')?>">
            <span class="gidro__colors_name"><?=$item->name?></span>
        </div>
    <?php endforeach; ?>
    </div>

</div>
<?php } ?>

<?php  $similar = $this->getRelatedProducts($page); ?>
<div class="center-wrap pt-2">
  <h2 class="right-slide__blockH2">Рекомендуем обратить внимание</h2>  
    <div class="catalog-list">
        <?php foreach($similar as $category): ?>
            <?= $this->render($category, 'content/catalog/preview') ?>
        <?php endforeach; ?>
    </div>
</div>
<?php if($page->getValue('galereya_proektov')){ $list = umiObjectsCollection::getInstance()->getGuidedItems($page->getValue('galereya_proektov'));$galereya_proektov = $this->vsk_objById(array_keys($list));  ?>
<div class="center-wrap pt-2">
    <h2 class="right-slide__blockH2">Галерея проектов</h2>

    <div style="display: flex;flex-wrap: wrap;">
    <?php foreach($galereya_proektov as $item): ?>
        <div class="gidro__project">
            <img data-fancybox="proekty" data-src="<?=$item->getValue('photo')?>" src="<?=$item->getValue('photo')?>">
            <span><?=str_replace('no name','',$item->name)?></span>
        </div>
    <?php endforeach; ?>
    </div>

</div>
<?php } ?>


<div class="center-wrap pt-2">
  <div class="article" style="padding-top:50px">
  <?=$page->getValue('content')?>
 </div>
</div>
