<section class="offer">
  <div class="offer__header">
    <img src="dist/assets/images/1700.png" alt="Обложка страницы">
    <div class="offer__header-content">
      <p>КОММЕРЧЕСКОЕ ПРЕДЛОЖЕНИЕ</p>
      <img src="dist/assets/images/aquabioraphy_title.svg" alt="">
      <h4>Royal <span>12037</span></h4>
      <a class="btn btn--primary"><svg width="16" height="16" viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg">
          <g clip-path="url(#clip0)">
            <path d="M14.3333 12H12.3333C12.1493 12 12 11.8507 12 11.6667C12 11.4827 12.1493 11.3333 12.3333 11.3333H14.3333C14.8847 11.3333 15.3333 10.8847 15.3333 10.3333V5.66667C15.3333 5.11533 14.8847 4.66667 14.3333 4.66667H1.66667C1.11533 4.66667 0.666667 5.11533 0.666667 5.66667V10.3333C0.666667 10.8847 1.11533 11.3333 1.66667 11.3333H3.66667C3.85067 11.3333 4 11.4827 4 11.6667C4 11.8507 3.85067 12 3.66667 12H1.66667C0.747333 12 0 11.252 0 10.3333V5.66667C0 4.748 0.747333 4 1.66667 4H14.3333C15.2527 4 16 4.748 16 5.66667V10.3333C16 11.252 15.2527 12 14.3333 12Z" fill="white" />
            <path d="M9.66732 14H5.66732C5.48332 14 5.33398 13.8506 5.33398 13.6666C5.33398 13.4826 5.48332 13.3333 5.66732 13.3333H9.66732C9.85132 13.3333 10.0007 13.4826 10.0007 13.6666C10.0007 13.8506 9.85132 14 9.66732 14Z" fill="white" />
            <path d="M9.66732 12.6667H5.66732C5.48332 12.6667 5.33398 12.5173 5.33398 12.3333C5.33398 12.1493 5.48332 12 5.66732 12H9.66732C9.85132 12 10.0007 12.1493 10.0007 12.3333C10.0007 12.5173 9.85132 12.6667 9.66732 12.6667Z" fill="white" />
            <path d="M7.00065 11.3333H5.66732C5.48332 11.3333 5.33398 11.184 5.33398 11C5.33398 10.816 5.48332 10.6667 5.66732 10.6667H7.00065C7.18465 10.6667 7.33398 10.816 7.33398 11C7.33398 11.184 7.18465 11.3333 7.00065 11.3333Z" fill="white" />
            <path d="M12.334 4.66667C12.15 4.66667 12.0007 4.51733 12.0007 4.33333V1.66667C12.0007 1.11533 11.552 0.666667 11.0007 0.666667H5.00065C4.44932 0.666667 4.00065 1.11533 4.00065 1.66667V4.33333C4.00065 4.51733 3.85132 4.66667 3.66732 4.66667C3.48332 4.66667 3.33398 4.51733 3.33398 4.33333V1.66667C3.33398 0.748 4.08132 0 5.00065 0H11.0007C11.92 0 12.6673 0.748 12.6673 1.66667V4.33333C12.6673 4.51733 12.518 4.66667 12.334 4.66667Z" fill="white" />
            <path d="M11.0007 16H5.00065C4.08132 16 3.33398 15.252 3.33398 14.3334V9.00002C3.33398 8.81602 3.48332 8.66669 3.66732 8.66669H12.334C12.518 8.66669 12.6673 8.81602 12.6673 9.00002V14.3334C12.6673 15.252 11.92 16 11.0007 16ZM4.00065 9.33335V14.3334C4.00065 14.8847 4.44932 15.3334 5.00065 15.3334H11.0007C11.552 15.3334 12.0007 14.8847 12.0007 14.3334V9.33335H4.00065Z" fill="white" />
          </g>
          <defs>
            <clipPath id="clip0">
              <rect width="16" height="16" fill="white" />
            </clipPath>
          </defs>
        </svg>
        Напечатать предложение</a>
    </div>
  </div>
  <div class="center-wrap offer__parties offer__block">
      <div class="offer__party">
        <span class="offer__party_header">Кому</span>
        <h3 class="offer__party_title">Александр</h3>
        <p class="offer__party_details">+7 (960) 271-17-70</p>
        <p class="offer__party_details">krankina@tophouse.ru</p>
        <p class="offer__party_details">Всеволожск</p>
      </div>
      <div class="offer__party">
        <span class="offer__party_header">Ваш менеджер</span>
        <h3 class="offer__party_title">Никита Джигурда</h3>
        <p class="offer__party_details">+7 (911) 000-86-13</p>
        <p class="offer__party_details">krankina@tophouse.ru</p>
        <img src="dist/assets/images/offer_manager.png" alt="Менеджер">
      </div>
      <div class="offer__party">
        <span class="offer__party_header">Предложение</span>
        <h3 class="offer__party_title">КП от 03.06.2021</h3>
        <p class="offer__party_details">Действительно в течении 3х рабочих дней.</p>
        <p class="offer__party_details">Курс евро ЦБ: 89,69 руб.</p>
      </div>
  </div>
  <div class="center-wrap offer__banner offer__block">
    <a href="#" class="offer__banner_link">Скидка 20% на павильон Aura covers при покупке бассейна</a>
  </div>

  <div class="center-wrap offer__pool offer__block">
  <h3 class="offer__pool_name">Cristal Royal <span>12037</span></h3>
  <div class="offer__pool_params">
    <div class="offer__pool_img">
      <img src="dist/assets/images/royal_grani.png" alt="">
    </div>
    <div class="offer__pool_param">
      <h2>12</h2>
      <span>Длина, м</span>
    </div>
    <div class="offer__pool_param">
      <h2>3,7</h2>
      <span>Ширина, м</span>
    </div>
    <div class="offer__pool_param">
      <h2>1,4 - 1,75</h2>
      <span>Глубина, м</span>
    </div>
    <div class="offer__pool_param">
      <h2>28</h2>
      <span>Объем чаши, м.куб</span>
    </div>
  </div>
  <p class="offer__pool_color">Цвет: <span>Grani Cristal 6</span></p>
  <a class="offer__pool_chertezh" href="#">Показать чертеж</a>
  </div>

  <div class="offer__description center-wrap">
    <div class="offer__description_title offer__toggle" data-block="about">
      <h2>Описание модели</h2>
      <svg width="18px" height="17px" xmlns="http://www.w3.org/2000/svg">
        <path d="M17.7071 0.292893C18.0676 0.653377 18.0953 1.22061 17.7903 1.6129L17.7071 1.70711L9.70711 9.70711C9.34662 10.0676 8.77939 10.0953 8.3871 9.7903L8.29289 9.70711L0.292892 1.70711C-0.0976315 1.31658 -0.0976315 0.683417 0.292892 0.292893C0.653376 -0.0675913 1.22061 -0.0953212 1.6129 0.209704L1.70711 0.292893L9 7.58579L16.2929 0.292893C16.6834 -0.0976309 17.3166 -0.0976309 17.7071 0.292893Z" fill="#000" />
      </svg>
    </div>
    <div class="offer__description_content hidden" data-block="about">
    Композитный бассейн ROYAL – одна из популярнейших линеек производства Аквабиография. Многие люди выбрали ROYAL из-за его классической формы и универсальных функций. Наша компания представляет четыре доступных в линейке модели.
    ROYAL предлагает роскошь и стиль, как никто другой. Четкие линии, грандиозный вход и переменная глубина чаши делают ROYAL идеальным бассейном в любой обстановке.
    Главным и несравнимым достоинством ROYAL безусловно является классическая римская лестница. Она является как парадным входом в бассейн, так и заметным украшением чаши в целом. Размер ступеней дает возможность с легкостью пользоваться бассейном людям всех возрастов и комплекций. При желании ступени можно оснастить диодной подсветкой, чтобы вариант исполнения Вашего бассейна стал эксклюзивным и неповторимым.
    </div>
  </div>
  <div class="offer__description center-wrap offer__block">
    <div class="offer__description_title offer__toggle" data-block="cristal">
      <h2>Что означает Cristal</h2>
      <svg width="18px" height="17px" xmlns="http://www.w3.org/2000/svg">
        <path d="M17.7071 0.292893C18.0676 0.653377 18.0953 1.22061 17.7903 1.6129L17.7071 1.70711L9.70711 9.70711C9.34662 10.0676 8.77939 10.0953 8.3871 9.7903L8.29289 9.70711L0.292892 1.70711C-0.0976315 1.31658 -0.0976315 0.683417 0.292892 0.292893C0.653376 -0.0675913 1.22061 -0.0953212 1.6129 0.209704L1.70711 0.292893L9 7.58579L16.2929 0.292893C16.6834 -0.0976309 17.3166 -0.0976309 17.7071 0.292893Z" fill="#000" />
      </svg>
    </div>
    <div class="offer__description_content hidden" data-block="cristal">
    Композитный бассейн ROYAL – одна из популярнейших линеек производства Аквабиография. Многие люди выбрали ROYAL из-за его классической формы и универсальных функций. Наша компания представляет четыре доступных в линейке модели.
    ROYAL предлагает роскошь и стиль, как никто другой. Четкие линии, грандиозный вход и переменная глубина чаши делают ROYAL идеальным бассейном в любой обстановке.
    Главным и несравнимым достоинством ROYAL безусловно является классическая римская лестница. Она является как парадным входом в бассейн, так и заметным украшением чаши в целом. Размер ступеней дает возможность с легкостью пользоваться бассейном людям всех возрастов и комплекций. При желании ступени можно оснастить диодной подсветкой, чтобы вариант исполнения Вашего бассейна стал эксклюзивным и неповторимым.
    </div>
  </div>

  <div class="offer__expenses offer__block">
    <div class="center-wrap">
      <div class="offer__expense">
        <div class="offer__expense_name">Модель бассейна</div>
        <div class="offer__expense_spacing"></div>
        <div class="offer__expense_cost">1 090 000р.</div>
      </div>
      <div class="offer__expense">
        <div class="offer__expense_name">Утепление Thermopool</div>
        <div class="offer__expense_spacing"></div>
        <div class="offer__expense_cost">115 000р.</div>
      </div>
      <div class="offer__expense">
        <div class="offer__expense_name">Утепление Thermopool</div>
        <div class="offer__expense_spacing"></div>
        <div class="offer__expense_cost">115 000р.</div>
      </div>
      <div class="offer__expense">
        <div class="offer__expense_name">Утепление Thermopool</div>
        <div class="offer__expense_spacing"></div>
        <div class="offer__expense_cost">115 000р.</div>
      </div>
      <div class="offer__expense">
        <div class="offer__expense_name">Утепление Thermopool</div>
        <div class="offer__expense_spacing"></div>
        <div class="offer__expense_cost">115 000р.</div>
      </div>
      <div class="offer__expenses_summary">
        <div class="offer__expense_name">Итого по категории</div>
        <div class="offer__expense_spacing"></div>
        <div class="offer__expense_cost">1 935 000р.</div>
      </div>
    </div>
  </div>
  <div class="center-wrap offer__banner offer__block">
    <a href="#" class="offer__banner_link">Скидка 20% на павильон Aura covers при покупке бассейна</a>
  </div>

  <div class="offer__description center-wrap offer__description_flex">
    <div>
      <div class="offer__description_title">
        <h2>Основное оборудование</h2>
      </div>
      <div class="offer__description_content offer__description_contentWithImg">
      Основное оборудование это набор, необходимый для каждого бассейна. Для забора воды с поверхности предназначен скиммер, а с нижних слоев воды - донный забор. 
      По трубам вода поступает в фильтровальную установку, где происходит ее механическая очистка. 
      Очищенная вода подается в бассейн через возвратные форсунки. Для подводного освещения в бассейн устанавливают прожектор.
      </div>
    </div>
    <div>
      <img src="dist/assets/images/offer_pool.png" alt="">
    </div>
  </div>
  <div class="offer__expenses offer__block">
    <div class="center-wrap">
      <div class="offer__expense offer__expense_title offer__expense_modified">
        <div class="offer__expense_text">Наименование</div>
        <div class="offer__expense_text">Кол-во</div>
        <div class="offer__expense_text">Скидка, руб</div>
        <div class="offer__expense_text">Сумма со скидкой, руб.</div>
      </div>
      <div class="offer__expense offer__expense_modified">
        <div class="offer__expense_text">Трубная обвязка Ниагара 6 (не далее 5 м)</div>
        <div class="offer__expense_text">1 шт.</div>
        <div class="offer__expense_text">0</div>
        <div class="offer__expense_text">37 759 р.</div>
      </div>
      <div class="offer__expense offer__expense_modified">
        <div class="offer__expense_text">Трубная обвязка Ниагара 6 (не далее 5 м)</div>
        <div class="offer__expense_text">1 шт.</div>
        <div class="offer__expense_text">0</div>
        <div class="offer__expense_text">37 759 р.</div>
      </div>
      <div class="offer__expense offer__expense_modified">
        <div class="offer__expense_text">Трубная обвязка Ниагара 6 (не далее 5 м)</div>
        <div class="offer__expense_text">1 шт.</div>
        <div class="offer__expense_text">0</div>
        <div class="offer__expense_text">37 759 р.</div>
      </div>
      <div class="offer__expense offer__expense_modified">
        <div class="offer__expense_text">Трубная обвязка Ниагара 6 (не далее 5 м)</div>
        <div class="offer__expense_text">1 шт.</div>
        <div class="offer__expense_text">0</div>
        <div class="offer__expense_text">37 759 р.</div>
      </div>
      <div class="offer__expense offer__expense_modified">
        <div class="offer__expense_text">Трубная обвязка Ниагара 6 (не далее 5 м)</div>
        <div class="offer__expense_text">1 шт.</div>
        <div class="offer__expense_text">0</div>
        <div class="offer__expense_text">37 759 р.</div>
      </div>
      <div class="offer__expenses_summary offer__expense offer__expense_modified">
        <div class="offer__expense_text">Итого</div>
        <div class="offer__expense_text">190 839 р.</div>
      </div>
    </div>
  </div>

  <div class="offer__description center-wrap offer__description_flex">
    <div>
      <div class="offer__description_title">
        <h2>Дополнительное оборудование</h2>
      </div>
      <div class="offer__description_content offer__description_contentWithImg">
      Чтобы повысить комфорт Вашего пребывания в бассейне, мы можем снабдить его дополнительным оборудованием. 
      Это может быть нагрев воды в бассейне, системы автоматической дезинфекции, поручни и лестницы, водопады и противотоки, роботы-очистители. 
      Также можно установить различные развлечения для досуга детей: горки и трамплины.
      </div>
    </div>
    <div>
      <img src="dist/assets/images/offer_pool2.png" alt="">
    </div>
  </div>
  <div class="offer__expenses offer__block">
    <div class="center-wrap">
      <div class="offer__expense offer__expense_title offer__expense_modified">
        <div class="offer__expense_text">Наименование</div>
        <div class="offer__expense_text">Кол-во</div>
        <div class="offer__expense_text">Скидка, руб</div>
        <div class="offer__expense_text">Сумма со скидкой, руб.</div>
      </div>
      <div class="offer__expense offer__expense_modified">
        <div class="offer__expense_text">Трубная обвязка Ниагара 6 (не далее 5 м)</div>
        <div class="offer__expense_text">1 шт.</div>
        <div class="offer__expense_text">0</div>
        <div class="offer__expense_text">37 759 р.</div>
      </div>
      <div class="offer__expense offer__expense_modified">
        <div class="offer__expense_text">Трубная обвязка Ниагара 6 (не далее 5 м)</div>
        <div class="offer__expense_text">1 шт.</div>
        <div class="offer__expense_text">0</div>
        <div class="offer__expense_text">37 759 р.</div>
      </div>
      <div class="offer__expense offer__expense_modified">
        <div class="offer__expense_text">Трубная обвязка Ниагара 6 (не далее 5 м)</div>
        <div class="offer__expense_text">1 шт.</div>
        <div class="offer__expense_text">0</div>
        <div class="offer__expense_text">37 759 р.</div>
      </div>
      <div class="offer__expense offer__expense_modified">
        <div class="offer__expense_text">Трубная обвязка Ниагара 6 (не далее 5 м)</div>
        <div class="offer__expense_text">1 шт.</div>
        <div class="offer__expense_text">0</div>
        <div class="offer__expense_text">37 759 р.</div>
      </div>
      <div class="offer__expense offer__expense_modified">
        <div class="offer__expense_text">Трубная обвязка Ниагара 6 (не далее 5 м)</div>
        <div class="offer__expense_text">1 шт.</div>
        <div class="offer__expense_text">0</div>
        <div class="offer__expense_text">37 759 р.</div>
      </div>
      <div class="offer__expenses_summary offer__expense offer__expense_modified">
        <div class="offer__expense_text">Итого</div>
        <div class="offer__expense_text">190 839 р.</div>
      </div>
    </div>
  </div>

  <div class="offer__complect offer__block">
    <h2 class="offer__complect_title">Комплектация</h2>
    <div class="offer__complect_flex">
      <div class="offer__complect_parts">
        <div>
          <p class="offer__complect_part"><span>Чаша</span><span>1 935 000р.</span></p>
          <p class="offer__complect_part"><span>Основное оборудование</span><span>535 000р.</span></p>
          <p class="offer__complect_part"><span>Дополнительное оборудование</span><span>190 839р.</span></p>
        </div>
        <div>
          <p class="offer__complect_part"><span>ИТОГО:</span><span>2 735 000р.</span></p>
        </div>
      </div>
    </div>
  </div>

</section>

<footer class="footer">
  <div class="center-wrap">
    <div class="footer__wrap">
      <div class="footer__address"><span class="footer__address-city mobile--hide">Санкт-Петербург,</span>ул.Бассейная,д.73,корпус 1</div>
      <div class="footer__center">
        <div class="footer__contract mobile--hide" onclick="show_popup(&quot;contract&quot;)">Договор оферты</div>
        <div class="footer__privacy mobile--hide" onclick="show_popup(&quot;privacy&quot;)">Политика конфиденциальности</div>
      </div>
      <p class="footer__copyright">© tvoybasseyn.ru, 2013 - 2021 год</p>
    </div>
  </div>
</footer>