<?php

$page = $variables['page'];

$price = 0;
if($page->getValue('stoimost')) $price = str_replace(' ','',$page->getValue('stoimost'));
if($price == 0) $price = '';
else $price = number_format($price, 0, ',', ' ').' ₽';
$price2 = 0;
if($page->getValue('cena_cristal')) $price2 = str_replace(' ','',$page->getValue('cena_cristal'));
if($price2 == 0) $price2 = '';
else $price2 = number_format($price2, 0, ',', ' ').' ₽';

$settings = $this->getSettingsContainer();
$objId = $settings->getValue('uslugi_v_tovare');
$uslugi = umiObjectsCollection::getInstance()->getGuidedItems($objId);

$fabrikaId = $page->getValue('fabrika');
$fabrika = $this->getRelation($fabrikaId);

$product__tabs = ['desc'=>'Описание'];
if($fabrikaId==53032) $product__tabs['options'] = 'Опции';
if($fabrikaId==53032) $product__tabs['colors'] = 'Цвет';
if($fabrikaId==53032&&$page->getValue('chertezh')) $product__tabs['chertezh'] = 'Чертеж';

if($fabrikaId==63238||$fabrikaId==76607) $product__tabs['pavPrice'] = 'Прайс-лист';
$product__tabs['delivery'] = 'Доставка и оплата';

?>

<style>
    .manufacturer__text{
        font-size: 1.2rem;
        line-height: 1.53077;
        color: #484848;
        max-width: 26rem;
        margin-bottom: 3rem;
    }
</style>

<section class="product" id="product-page">
 <div class="product__top">
    <div class="center-wrap">
      <div class="product__title"><?= $this->escape($variables['header']) ?></div>
      <div class="product__inner">
        <?= $this->render($variables, 'layout/header/breadcrumbs') ?>
        <div class="product__inner-right mobile--hide">
          <div class="product__inner-postpone comparisons comparisons--bg comparisons--heart">
            <svg width="14" height="14" viewBox="0 0 14 14" fill="none" xmlns="http://www.w3.org/2000/svg">
              <path d="M6.61741 2.30257L7 2.75726L7.38259 2.30257C8.05457 1.50392 9.08565 1 10.15 1C12.0242 1 13.5 2.48491 13.5 4.39646C13.5 5.57313 12.9816 6.67886 11.9705 7.92993C10.9535 9.18832 9.48939 10.5331 7.67692 12.1965L7.67621 12.1971L6.99871 12.8213L6.32347 12.2039L6.32263 12.2031C4.51044 10.5365 3.04657 9.19014 2.02961 7.93094C1.01841 6.67889 0.5 5.57314 0.5 4.39646C0.5 2.48491 1.97578 1 3.85 1C4.91435 1 5.94543 1.50392 6.61741 2.30257Z"></path>
            </svg>Отложить
          </div>
        </div>
      </div>
    </div>
  </div>
  
  <?php if($fabrikaId==63238||$fabrikaId==76607): ?>
    <?= $this->render($variables, 'content/pools/page/pavilion') ?>
  <?php else: ?>
    <?= $this->render($variables, 'content/pools/page/poolModel') ?>
  <?php endif; ?>

  <div class="product__info-wrap">
    <div class="center-wrap">


<div class="product__info">
  <div style="width:100%">
    <div class="product__tabs toogles__wrap">
      <div class="product__tabs-row mobile--hide">
        <?php $i=1; foreach($product__tabs as $key => $tab): ?>
          <div class="product__tabs-item toogles__item-title <?=($i == 1)?'toogles__item-title--active':''?>" data-toogles="<?=$i++?>"><?=$tab?></div>
        <?php endforeach; ?>
      </div>
      <div class="product__tabs-slider desktop--hide">
        <div class="swiper-container">
          <div class="swiper-wrapper">
            <?php $i=1; foreach($product__tabs as $key => $tab): ?>

              <div class="swiper-slide">
                <div class="product__tabs-item toogles__item-title <?=($i == 1)?'toogles__item-title--active':''?>" data-toogles="<?=$i++?>"><?=$tab?></div>
              </div>
            <?php endforeach; ?>
            
          </div>
        </div>
      </div>
      <?php $i=1; foreach($product__tabs as $key => $tab): ?>
      <div class="toogles__item <?=($i == 1)?'toogles__item--active':''?>" data-toogles="<?=$i++?>">
        <div class="toogles__item-content" style="<?=($i == 2)?'display: block;':''?>">
          <div>
            <div class="product__tabs-tab" style="margin:0;max-width:100%">

            <?= $this->render($variables, 'blocks/tabs/'.$key) ?>

            </div> 
          </div>
        </div>
      </div>
      <?php endforeach; ?>
    </div>
  </div>

  <?php if($fabrikaId){ ?>
    <div class="product__column poolPage_column" style="position: sticky;top: 86px;display: table;">  
      <div class="product__price">
        <div class="price"> 
          <?php if($price){ ?>
            <a style="font-size: 1.6rem;" data-fancybox data-src="#linerDesc" href="javascript:;"><!--<u>LINER</u>-->
            <p><?=$price?></p></a>
          <?php } ?>
          <!-- <?php if($price2){ ?>
            <a style="font-size: 1.6rem;" data-fancybox data-src="#cristalDesc" href="javascript:;"><u>CRISTAL</u>
            <p><?=$price2?></p></a>
          <?php } ?> -->
        </div>
      </div>
      <div class="product__row">
        <div class="product__row-basket1">
          <div class="basket basket--blue" onclick="$('#callback input[name=&quot;system_form_id&quot;]').val(236);$('#callback .popup-form__title').text('Консультация по бассейну <?=$page->name?>');show_popup('callback')">
            <span>Заказать консультацию</span>
          </div>
        </div>
      </div>
      <div class="product__discount mobile--hide">
        <div class="discount">
          <svg viewBox="0 0 26 24" fill="none" xmlns="http://www.w3.org/2000/svg">
            <path d="M8.64144 7.36614L12.1263 0.525577C12.4833 -0.175192 13.5167 -0.175192 13.8737 0.525577L17.3586 7.36614L25.1643 8.4567C25.9637 8.56839 26.2832 9.51814 25.7047 10.0631L20.059 15.3818L21.3918 22.8971C21.5283 23.6667 20.6925 24.2533 19.978 23.8894L13 20.3357L6.02205 23.8894C5.3072 24.2534 4.47114 23.6661 4.60835 22.8963L5.94771 15.3818L0.295738 10.0635C-0.283268 9.51868 0.0360775 8.56842 0.835721 8.4567L8.64144 7.36614Z"></path>
          </svg><a class="discount__link mobile--hide" href="">Получите скидку 3% от суммы заказа</a>
        </div>
      </div>

      <?= $this->render($variables, 'blocks/product/props') ?>
  </div>
  <?php } ?>
</div>  




    </div>
  </div> 
</section>    


<style>

.services__text {
    max-width: 100%;
    padding-right: 30px;
}
.nav-tabs > li {
    margin-bottom: 0!important;
}
@media screen and (max-width:768px){
  .services__item {
    width: 100%;
  }
}
</style>