<section class="product" id="product-page">
    <div class="product__aquabioraphy">
        <img src="dist/assets/images/poolPage_royal.png" alt="">
        <div class="product__aquabioraphy-titles">
            <h2 class="product__aquabioraphy-title">Аквабиография</h2>
            <h2 class="product__aquabioraphy-serie">Art</h2>
        </div>
    </div>
    <div class="center-wrap product__main">
        <div class="product__info2">    
            <div class="product__info2-model">
                <div>
                    <h4>Модель</h4>
                    <h2>Art <a class="open_modelsDropdown">6530</a></h2>
                </div>
                <div class="product__info2-scheme">
                <img src="dist/assets/images/poolPage_scheme.png" alt="">
                    <span class="product__info2-length">12 м</span>
                    <span class="product__info2-width">3,7 м</span>
                    <span class="product__info2-depth">Глубина <span>1.4-1.9 м</span></span>
                </div>
            </div>
            <div class="product__dropdowns product__modelDropdowns">
                <div class="product__dropdown">
                    <div>
                        <h4>Модель</h4>
                        <h2>Art 6530</h2>
                    </div>
                    <div>
                        <h4>Liner</h4>
                        <h2>670 000 ₽</h2>
                    </div>
                    <div>
                        <h4>Cristal</h4>
                        <h2>940 000 ₽</h2>
                    </div>
                    <div>
                        <img src="dist/assets/images/poolPage_scheme.png" alt="">
                    </div>
                </div>
                <div class="product__dropdown">
                <div>
                        <h4>Модель</h4>
                        <h2>Art 4025</h2>
                    </div>
                    <div>
                        <h4>Liner</h4>
                        <h2>670 000 ₽</h2>
                    </div>
                    <div>
                        <h4>Cristal</h4>
                        <h2>940 000 ₽</h2>
                    </div>
                    <div>
                        <img src="dist/assets/images/poolPage_scheme.png" alt="">
                    </div>
                </div>
            </div>
            <p class="product__info2-description">
            Композитный бассейн ROYAL – одна из популярнейших линеек производства Аквабиография. Многие люди выбрали ROYAL из-за его классической формы и универсальных функций. Наша компания представляет четыре доступных в линейке модели.
            ROYAL предлагает роскошь и стиль, как никто другой. Четкие линии, грандиозный вход и переменная глубина чаши делают ROYAL идеальным бассейном в любой обстановке.
            Главным и несравнимым достоинством ROYAL безусловно является классическая римская лестница. Она является как парадным входом в бассейн, так и заметным украшением чаши в целом. Размер ступеней дает возможность с легкостью пользоваться бассейном людям всех возрастов и комплекций. При желании ступени можно оснастить диодной подсветкой, чтобы вариант исполнения Вашего бассейна стал эксклюзивным и неповторимым.
            Традиционный модельный ряд ROYAL включает в себя 12, 10, 9 и 8 метровые версии. Во всех моделях реализована переменная глубина чаши с 1,4 – 1,7 м. и только в 12 метровой чаше глубина достигает почти 2-х метров.
            </p>
        </div>
        <div class="product__purchase">
            <div class="product__purchase-prices">
                <h4>Стоимость Liner</h4>
                <h3>670 000 ₽</h3>
                <h4>Стоимость Cristal</h4>
                <h3>940 000 ₽</h3>
            </div>
            <div class="product__purchase-links">
                <button class="btn btn--blue">Консультация</button>
                <button>В калькулятор</button>
                <a href="">Скачать чертеж</a>
                <div class="product__purchase-discount">
                % Доступно со скидкой
                </div>
            </div>
        </div>
    </div>
    <div class="product__dropdowns">
        <div class="product__dropdown">
            <h2 class="product__dropdown-title">Варианты исполнения</h2>
            <div class="product__dropdown-icon">
                <svg width="18px" height="10px" xmlns="http://www.w3.org/2000/svg">
                    <path d="M17.7071 0.292893C18.0676 0.653377 18.0953 1.22061 17.7903 1.6129L17.7071 1.70711L9.70711 9.70711C9.34662 10.0676 8.77939 10.0953 8.3871 9.7903L8.29289 9.70711L0.292892 1.70711C-0.0976315 1.31658 -0.0976315 0.683417 0.292892 0.292893C0.653376 -0.0675913 1.22061 -0.0953212 1.6129 0.209704L1.70711 0.292893L9 7.58579L16.2929 0.292893C16.6834 -0.0976309 17.3166 -0.0976309 17.7071 0.292893Z" fill="#000"/>
                </svg>
            </div>
        </div>
        <div class="product__dropdown">
            <h2 class="product__dropdown-title">Дополнительные опции</h2>
            <div class="product__dropdown-icon">
                <svg width="18px" height="10px" xmlns="http://www.w3.org/2000/svg">
                    <path d="M17.7071 0.292893C18.0676 0.653377 18.0953 1.22061 17.7903 1.6129L17.7071 1.70711L9.70711 9.70711C9.34662 10.0676 8.77939 10.0953 8.3871 9.7903L8.29289 9.70711L0.292892 1.70711C-0.0976315 1.31658 -0.0976315 0.683417 0.292892 0.292893C0.653376 -0.0675913 1.22061 -0.0953212 1.6129 0.209704L1.70711 0.292893L9 7.58579L16.2929 0.292893C16.6834 -0.0976309 17.3166 -0.0976309 17.7071 0.292893Z" fill="#000"/>
                </svg>
            </div>
        </div>
        <div class="product__dropdown">
            <h2 class="product__dropdown-title">Доступные цвета</h2>
            <div class="product__dropdown-icon">
                <svg width="18px" height="10px" xmlns="http://www.w3.org/2000/svg">
                    <path d="M17.7071 0.292893C18.0676 0.653377 18.0953 1.22061 17.7903 1.6129L17.7071 1.70711L9.70711 9.70711C9.34662 10.0676 8.77939 10.0953 8.3871 9.7903L8.29289 9.70711L0.292892 1.70711C-0.0976315 1.31658 -0.0976315 0.683417 0.292892 0.292893C0.653376 -0.0675913 1.22061 -0.0953212 1.6129 0.209704L1.70711 0.292893L9 7.58579L16.2929 0.292893C16.6834 -0.0976309 17.3166 -0.0976309 17.7071 0.292893Z" fill="#000"/>
                </svg>
            </div>
        </div>
        <div class="product__dropdown">
            <h2 class="product__dropdown-title">Готовые проекты</h2>
            <div class="product__dropdown-icon">
                <svg width="18px" height="10px" xmlns="http://www.w3.org/2000/svg">
                    <path d="M17.7071 0.292893C18.0676 0.653377 18.0953 1.22061 17.7903 1.6129L17.7071 1.70711L9.70711 9.70711C9.34662 10.0676 8.77939 10.0953 8.3871 9.7903L8.29289 9.70711L0.292892 1.70711C-0.0976315 1.31658 -0.0976315 0.683417 0.292892 0.292893C0.653376 -0.0675913 1.22061 -0.0953212 1.6129 0.209704L1.70711 0.292893L9 7.58579L16.2929 0.292893C16.6834 -0.0976309 17.3166 -0.0976309 17.7071 0.292893Z" fill="#000"/>
                </svg>
            </div>
        </div>
        <div class="product__dropdown">
            <h2 class="product__dropdown-title">Доставка и оплата</h2>
            <div class="product__dropdown-icon">
                <svg width="18px" height="10px" xmlns="http://www.w3.org/2000/svg">
                    <path d="M17.7071 0.292893C18.0676 0.653377 18.0953 1.22061 17.7903 1.6129L17.7071 1.70711L9.70711 9.70711C9.34662 10.0676 8.77939 10.0953 8.3871 9.7903L8.29289 9.70711L0.292892 1.70711C-0.0976315 1.31658 -0.0976315 0.683417 0.292892 0.292893C0.653376 -0.0675913 1.22061 -0.0953212 1.6129 0.209704L1.70711 0.292893L9 7.58579L16.2929 0.292893C16.6834 -0.0976309 17.3166 -0.0976309 17.7071 0.292893Z" fill="#000"/>
                </svg>
            </div>
        </div>
    </div>
    <div class="center-wrap product__series">
        <h2 class="product__series-headline">Другие модели</h2>
        <div class="product__series-previews">
            <div class="product__series-preview">
                <img src="dist/assets/images/poolPage_serie.png" alt="">
                <h2>Royal</h2>
            </div>
            <div class="product__series-preview">
                <img src="dist/assets/images/poolPage_serie.png" alt="">
                <h2>Supreme</h2>
            </div>
            <div class="product__series-preview">
                <img src="dist/assets/images/poolPage_serie.png" alt="">
                <h2>Hugo</h2>
            </div>
        </div>
    </div>
</section>