<?php 
$sale = $this->getProductsListFromCategory(325);
$isInSales = $this->findPositionInList($sale, $variables['header']);

$page = $variables['page'];

$price = 0;
if($page->getValue('stoimost')) $price = str_replace(' ','',$page->getValue('stoimost'));
if($price == 0) $price = '';
else $price = number_format($price, 0, ',', ' ').' ₽';
$price2 = 0;
if($page->getValue('cena_cristal')) $price2 = str_replace(' ','',$page->getValue('cena_cristal'));
if($price2 == 0) $price2 = '';
else $price2 = number_format($price2, 0, ',', ' ').' ₽';
?>


<section class="product" id="product-page">
    <div class="product__aquabioraphy">
        <img src="dist/assets/images/poolPage_royal.png" alt="">
        <div class="product__aquabioraphy-titles">
            <h2 class="product__aquabioraphy-title">Аквабиография</h2>
            <h2 class="product__aquabioraphy-serie"><?= ucfirst(strtolower(explode(' ', $this->escape($page->name))[0])) ?></h2>
        </div>
    </div>
    <div class="center-wrap product__main">
        <div class="product__dropdowns product__modelDropdowns">
            <div class="product__dropdown product__modelDropdown">
                <div>
                    <h4>Модель</h4>
                    <h2><?= ucfirst(strtolower(explode(' ', $this->escape($page->name))[0])) ?> <a class="toggle_modelsDropdown"><?= explode(' ', $this->escape($page->name))[1] ?></a></h2>
                </div>
                <div>
                    <h4>Liner</h4>
                    <h2>670 000 ₽</h2>
                </div>
                <div>
                    <h4>Cristal</h4>
                    <h2>940 000 ₽</h2>
                </div>
                <div>
                    <img src="dist/assets/images/poolPage_scheme.png" alt="">
                </div>
            </div>
            <div class="product__dropdown product__modelDropdown">
            <div>
                    <h4>Модель</h4>
                    <h2>Art 4025</h2>
                </div>
                <div>
                    <h4>Liner</h4>
                    <h2>670 000 ₽</h2>
                </div>
                <div>
                    <h4>Cristal</h4>
                    <h2>940 000 ₽</h2>
                </div>
                <div>
                    <img src="dist/assets/images/poolPage_scheme.png" alt="">
                </div>
            </div>
        </div>
        <div class="product__info2">    
            <div class="product__info2-model">
                <div>
                    <h4>Модель</h4>
                    <h2><?= ucfirst(strtolower(explode(' ', $this->escape($page->name))[0])) ?> <a class="toggle_modelsDropdown">
                    <?= explode(' ', $this->escape($page->name))[1] ?>
                    <svg width="13" height="10" viewBox="0 0 13 10" fill="none" xmlns="http://www.w3.org/2000/svg">
                        <path d="M6.5 10L0.870835 0.25L12.1292 0.250001L6.5 10Z" fill="#484848"/>
                    </svg>
                    </a></h2>
                </div>
                <div class="product__info2-scheme">
                <img src="<?=$page->getValue('scheme_with_params')?>" alt="">
                </div>
            </div>
            <div class="product__info2-description">
            <?=$page->getValue('content')?>
            </div>
        </div>
        <div class="product__purchase">
            <div class="product__purchase-prices">
                <h4>Стоимость Liner</h4>
                <h3><?=$price?></h3>
                <h4>Стоимость Cristal</h4>
                <h3><?=$price2?></h3>
            </div>
            <div class="product__purchase-links">
                <button class="btn btn--blue">Консультация</button>
                <button>В калькулятор</button>
                <a href="">Скачать чертеж</a>
                <?php if($isInSales): ?>
                <div class="product__purchase-discount">
                % Доступно со скидкой
                </div>
                <?php endif;?>
            </div>
        </div>
    </div>
    <div class="product__dropdowns">
        <div class="product__dropdown">
            <h2 class="product__dropdown-title">Варианты исполнения</h2>
            <div class="product__dropdown-icon">
                <svg width="18px" height="10px" xmlns="http://www.w3.org/2000/svg">
                    <path d="M17.7071 0.292893C18.0676 0.653377 18.0953 1.22061 17.7903 1.6129L17.7071 1.70711L9.70711 9.70711C9.34662 10.0676 8.77939 10.0953 8.3871 9.7903L8.29289 9.70711L0.292892 1.70711C-0.0976315 1.31658 -0.0976315 0.683417 0.292892 0.292893C0.653376 -0.0675913 1.22061 -0.0953212 1.6129 0.209704L1.70711 0.292893L9 7.58579L16.2929 0.292893C16.6834 -0.0976309 17.3166 -0.0976309 17.7071 0.292893Z" fill="#000"/>
                </svg>
            </div>
        </div>
        <!-- <div class="product__dropdown" style="display:flex">
        <div>
            <div class="article" style="margin:0;">
                <h2 style="margin-bottom: 60px;">Вариант исполнения LINER®</h2>
                <h4>FIBERGLASS POOL</h4>
                <p>Базовый вариант исполнения. Cмесь полиэфирной смолы, армирующих материалов и барьерный винилэфирный слой. Отличный состав по своим свойствам, который идеально подходит для создания стационарного бассейна. Тем более в такой чаше нет ни единого шва, что делает ее очень прочной. На выбор дается 2 цвета - белый и голубой. Гарантия на чаши в исполнении Liner составляет 15 лет.</p>
            </div> 
        </div>
        <div>
            <div class="article" style="margin:0;">
                <h2 style="margin-bottom: 60px;">Вариант исполнения CRISTAL®</h2>
                <h4>GLASS CRISTAL®</h4>
                <p>Прозрачный слой, созданный по новейшей технологии для создания непревзойденного глянцевого эффекта. Придаёт насыщенный зеркальный оттенок и глубину цвету. Надежно защищает от хим. реагентов, механического воздействия и ультрофиолетового излучения. Гарантия на чаши в исполнении Cristal - 30 лет.</p>
    
                <h4>GRANI CRISTAL®</h4>
                <p>Инновационный материал в основе которого лежит технология литиевого гранита. Наши дизайнеры собрали девять цветов которые погрузят вас в мир натурального камня. Гранит, мрамор которые подчёркнут монументальность, престижность и индивидуальность вашего дизайнерского решения.</p>
    
                <h4>CERAMO CRISTAL®</h4>
                <p>Керамический слой, повышающий жесткость конструкции. Дополнительный гидроизоляционный слой, уменьшает теплопотери до 20%</p>
            </div> 
        </div>
        </div> -->
        <div class="product__dropdown">
            <h2 class="product__dropdown-title">Дополнительные опции</h2>
            <div class="product__dropdown-icon">
                <svg width="18px" height="10px" xmlns="http://www.w3.org/2000/svg">
                    <path d="M17.7071 0.292893C18.0676 0.653377 18.0953 1.22061 17.7903 1.6129L17.7071 1.70711L9.70711 9.70711C9.34662 10.0676 8.77939 10.0953 8.3871 9.7903L8.29289 9.70711L0.292892 1.70711C-0.0976315 1.31658 -0.0976315 0.683417 0.292892 0.292893C0.653376 -0.0675913 1.22061 -0.0953212 1.6129 0.209704L1.70711 0.292893L9 7.58579L16.2929 0.292893C16.6834 -0.0976309 17.3166 -0.0976309 17.7071 0.292893Z" fill="#000"/>
                </svg>
            </div>
        </div>
        <div class="product__dropdown">
            <h2 class="product__dropdown-title">Доступные цвета</h2>
            <div class="product__dropdown-icon">
                <svg width="18px" height="10px" xmlns="http://www.w3.org/2000/svg">
                    <path d="M17.7071 0.292893C18.0676 0.653377 18.0953 1.22061 17.7903 1.6129L17.7071 1.70711L9.70711 9.70711C9.34662 10.0676 8.77939 10.0953 8.3871 9.7903L8.29289 9.70711L0.292892 1.70711C-0.0976315 1.31658 -0.0976315 0.683417 0.292892 0.292893C0.653376 -0.0675913 1.22061 -0.0953212 1.6129 0.209704L1.70711 0.292893L9 7.58579L16.2929 0.292893C16.6834 -0.0976309 17.3166 -0.0976309 17.7071 0.292893Z" fill="#000"/>
                </svg>
            </div>
        </div>
        <div class="product__dropdown">
            <h2 class="product__dropdown-title">Готовые проекты</h2>
            <div class="product__dropdown-icon">
                <svg width="18px" height="10px" xmlns="http://www.w3.org/2000/svg">
                    <path d="M17.7071 0.292893C18.0676 0.653377 18.0953 1.22061 17.7903 1.6129L17.7071 1.70711L9.70711 9.70711C9.34662 10.0676 8.77939 10.0953 8.3871 9.7903L8.29289 9.70711L0.292892 1.70711C-0.0976315 1.31658 -0.0976315 0.683417 0.292892 0.292893C0.653376 -0.0675913 1.22061 -0.0953212 1.6129 0.209704L1.70711 0.292893L9 7.58579L16.2929 0.292893C16.6834 -0.0976309 17.3166 -0.0976309 17.7071 0.292893Z" fill="#000"/>
                </svg>
            </div>
        </div>
        <div class="product__dropdown">
            <h2 class="product__dropdown-title">Доставка и оплата</h2>
            <div class="product__dropdown-icon">
                <svg width="18px" height="10px" xmlns="http://www.w3.org/2000/svg">
                    <path d="M17.7071 0.292893C18.0676 0.653377 18.0953 1.22061 17.7903 1.6129L17.7071 1.70711L9.70711 9.70711C9.34662 10.0676 8.77939 10.0953 8.3871 9.7903L8.29289 9.70711L0.292892 1.70711C-0.0976315 1.31658 -0.0976315 0.683417 0.292892 0.292893C0.653376 -0.0675913 1.22061 -0.0953212 1.6129 0.209704L1.70711 0.292893L9 7.58579L16.2929 0.292893C16.6834 -0.0976309 17.3166 -0.0976309 17.7071 0.292893Z" fill="#000"/>
                </svg>
            </div>
        </div>
    </div>
    <div class="center-wrap product__series">
        <h2 class="product__series-headline">Другие модели</h2>
        <div class="product__series-previews">
            <div class="product__series-preview">
                <img src="dist/assets/images/poolPage_serie.png" alt="">
                <h2>Royal</h2>
            </div>
            <div class="product__series-preview">
                <img src="dist/assets/images/poolPage_serie.png" alt="">
                <h2>Supreme</h2>
            </div>
            <div class="product__series-preview">
                <img src="dist/assets/images/poolPage_serie.png" alt="">
                <h2>Hugo</h2>
            </div>
        </div>
    </div>
</section>