<?php 
$page = $variables['page'];
$catalog = $this->getProductsListFromCategory($variables['pageId'],100);

?>
<div class="center-wrap pt-2">
    <?= $this->render($variables, 'layout/header/titleWithBread') ?>
</div>

<div class="series-list pt-2">
        <?php foreach($catalog['items'] as $category): ?>
            <?= $this->render($category, 'content/pools/series/preview') ?>
        <?php endforeach; ?>
</div>

<!--<div class="center-wrap pt-2">
    <div class="article pt-2">
        <?=$page->getValue('content')?>
    </div>
</div>-->

<script>
    var items = $(".series__model");

    items.each(function(){
        if($(this).data('image')){
            var $this = $(this);
            
            $(this).hover(function(){
                let active = $this.closest('.series__wrap').find('.series__itemHoverImg');
                let old = active.attr('src');
                active.show();
                active.attr('src',$(this).data('image'));
                active.toggleClass('series__itemHoverImg--visible');
                //active.css('visibility','visible');
                //active.opacity(1);
                //$(this).data('image',old);
            });

            // $(this).mouseout(function(){
            //     // let active = $this.closest('.series__wrap').find('.series__itemHoverImg');
            //     // let old = active.attr('src');
            //     // active.attr('src',$(this).data('image'));
            //     active.toggleClass('series__itemHoverImg--visible');
            //    // $(this).data('image',old);
            // });
        }
    });
</script>

