<?php 
$page = $variables['page'];
$catalog = $this->getProductsListFromCategory($variables['pageId'],100);

?>
<div class="center-wrap" style="padding-top: 2.1rem;">
    <?= $this->render($variables, 'layout/header/titleWithBread') ?>
</div>

<div class="series-list" style="padding-top: 2.1rem;">
        <?php foreach($catalog['items'] as $category): ?>
            <?= $this->render($category, 'content/pools/series/preview') ?>
        <?php endforeach; ?>
</div>

<div class="center-wrap" style="padding-top: 2.1rem;">
    <div class="article" style="padding-top: 2.1rem;">
        <?=$page->getValue('content')?>
    </div>
</div>

<script>
    var items = $(".series__model");

    items.each(function(){
        if($(this).data('image')){
            var $this = $(this);
            
            $(this).hover(function(){
                let active = $this.closest('.series__wrap').find('.series__itemHoverImg');
                let old = active.attr('src');
                active.show();
                active.attr('src',$(this).data('image'));
                active.toggleClass('series__itemHoverImg--visible');
                //active.css('visibility','visible');
                //active.opacity(1);
                //$(this).data('image',old);
            });

            // $(this).mouseout(function(){
            //     // let active = $this.closest('.series__wrap').find('.series__itemHoverImg');
            //     // let old = active.attr('src');
            //     // active.attr('src',$(this).data('image'));
            //     active.toggleClass('series__itemHoverImg--visible');
            //    // $(this).data('image',old);
            // });
        }
    });
</script>

<style>
    .series__name {
        position: absolute;
        top: 25px;
        left: 35px;
        color: #fff;
        font-weight: bold;
        font-size: 4.2rem;
        z-index: 2;
    }
    .series__itemHoverImg {
        position: absolute;
        height: 100%;
        width: 100%;
        object-fit: contain;
        z-index: 3;
        background: #fff;
        transition: all .8s;
        visibility: hidden;
        opacity: 0;
    }
    .series__itemHoverImg--visible {
        visibility: visible;
        opacity: 1;
    }
    .series__item {
        position:relative;
    }
    .series__modelsList {
        display: flex;
        flex-wrap: wrap;
        margin-bottom: 7rem;
        position: relative;
    }
    .series__modelImage {
        padding: 1rem 1rem;
    }
    .series__modelPrice {
        color: #353535;
        font-size: 1.7rem;
        font-weight: bold;
        padding: 1rem 2rem 0;
        display: block;
    }
    .series__modelName {
        color: #353535;
        font-size: 1.7rem;
        font-weight: 500;
        padding: 2rem 2rem 1rem;
        display: block;
    }
    .series__model .product__specifications {
        margin-top:1.5rem;
        padding: 0 2rem;
    }
    .series__model:hover {
        background: #f7f7f7;
        
    }
    .series__model {
        max-width: calc(100% / 5);
        padding: 2rem 1rem;
    }
    @media screen and (max-width:768px){
        .series__model {
            width:100%;
            max-width: 100%;
            padding:0;
        }
    }

    .series__modelsList-slider .swiper-wrapper{
        padding-bottom: 2.8rem;
    }
    .swiper-pagination {
        top: calc(100% - 1.2rem);
        left: 0;
        right: 0;
        z-index: 5;
        display: block;
    }
    .swiper-pagination-bullet {
        width: 1.2rem;
        height: 1.2rem;
        background: rgba(64,129,255,0.6);
        margin-right: 0.8rem;
        -webkit-transition: all 0.5s;
        -o-transition: all 0.5s;
        transition: all 0.5s;
    }
    .swiper-container-horizontal>.swiper-pagination-bullets .swiper-pagination-bullet {
        margin: 0 13px;
    }
</style>