<?php
/**
 * Кнопка "Добавить к сравнению".
 *
 * @var umiTemplaterPHP|ViewPhpExtension|DemomarketPhpExtension $this
 * @var iUmiHierarchyElement $variables
 */

$product = $variables;
$data = $this->macros('emarket', 'getCompareLink', [$product->getId()]);
?>

<a class="product__inner-comparison comparisons comparisons--bg " href="<?= $this->getProductComparisonLink($data) ?>">
	<svg viewBox="0 0 13 14" fill="none" xmlns="http://www.w3.org/2000/svg">
	<path fill-rule="evenodd" clip-rule="evenodd" d="M0.125 2.25004V0.833374H12.875V2.25004H0.125ZM0.125 7.20837V5.79171H12.875V7.20837H0.125ZM0.125 12.1667V10.75H5.79167V12.1667H0.125ZM12.875 10.75V12.1667H11.1042V13.9375H9.6875V12.1667H7.91667V10.75H9.6875V8.97921H11.1042V10.75H12.875Z"></path>
	</svg><?= $this->getComparisonMessage($data) ?>
</a>