<?php
/**
 * Страница товара:
 *   - Заголовок
 *   - Изображение и слайдер
 *   - Ценовой блок
 *   - Свойства товара
 *   - Социальные кнопки
 *   - Блок "С этим товаром покупают"
 *   - Блок "Похожие товары"
 *   - Блок "Вы недавно смотрели"
 *   - Комментарии
 *
 * @var umiTemplaterPHP|ViewPhpExtension|DemomarketPhpExtension $this
 * @var array $variables
 */
$parent = end($variables['parents']);
$product = $variables['page'];
$imageList = $this->getProductImageList($product);
$description = $product->getValue('description');
$propList = $this->getProductPropertyChunks($product);

$brandId = $product->getValue('brend');
$brand = $this->getRelation($brandId);

$cart = $this->macros('emarket', 'cart');
$variables['cartItems'] = $cart['items'];
?>

<section class="product" data-id="<?=$product->id?>">
<?= $this->render($variables, 'catalog/product/main/caption/index') ?>
 
  <div class="center-wrap"> 
    <div class="product__wrap toogles__wrap">
      <?php if(count($imageList)>1): ?>
        <?= $this->render($variables, 'catalog/product/main/slider')?>
      <?php else:?>
        <div class="product__img desktop--hide">
					<img src="<?= $imageList[0] ?>" style="object-fit: contain;" alt=""></a>
				</div>
      <?php endif;?>
      <div class="product__inner-right desktop--hide mobile--hide">
        <div class="product__inner-postpone comparisons comparisons--bg comparisons--heart">
          <svg viewBox="0 0 15 13" fill="none" xmlns="http://www.w3.org/2000/svg">
            <path d="M7.11941 1.92959L7.50008 2.37662L7.88076 1.92959C8.56104 1.13072 9.60647 0.625 10.6876 0.625C12.5931 0.625 14.0834 2.11531 14.0834 4.02083C14.0834 5.19534 13.5597 6.30011 12.5362 7.55141C11.507 8.80972 10.0253 10.1544 8.19129 11.8175L8.19058 11.8182L7.4988 12.4479L6.80926 11.825L6.80834 11.8241C4.97463 10.1578 3.4932 8.81153 2.46404 7.55242C1.44045 6.30014 0.916748 5.19535 0.916748 4.02083C0.916748 2.11531 2.40706 0.625 4.31258 0.625C5.39369 0.625 6.43912 1.13072 7.11941 1.92959Z"></path>
          </svg><span>В&nbsp;избранное</span>
        </div>
        <?= $this->render($product, 'catalog/product/main/price/actions/compare') ?>
      </div>
	  	<?php $i=1; foreach ($imageList as $image): ?>
			<div class="toogles__item mobile--hide <?=($i==1)?'toogles__item--active':''?>" data-toogles="<?=$i++?>">
				<div class="toogles__item-content" <?=($i==2)?'style="display:block"':''?>> 
				<div>
					<div class="product__img">
					<a rel="fancybox_group" href="<?= $image ?>" class="fancybox" data-fancybox="gallery"><img src="<?= $image ?>" style="object-fit: contain;" alt=""></a>
					</div>
				</div>
				</div>
			</div>
		<?php endforeach; ?>
      <div class="product__column anchors">
        <?= $this->render($product,  'catalog/product/main/price/trade_offers') ?>
        <?php if (!$this->hasTradeOffers($product->getId())): ?>
          <?= $this->render($product, 'catalog/product/preview/optioned/list') ?>
        <?php endif; ?>
        <div class="product__specifications">
          <div class="product__column-title">Характеристики</div>
          <p class="product__specifications-item">Артикул  — <span> <?= $product->getValue('articul')?></span></p>
          <?php $i=0; $more = false; foreach ($propList as $index => $chunk): ?>
            <?php foreach ($chunk as $property): if($i>=5) $more=true; if(empty($property['value']) || $i>=5) continue; $i++; ?>
              <p class="product__specifications-item"><?= $property['title'] ?>  — <span> <?= $property['value'] ?></span></p>
            <?php endforeach; ?>	
          <?php endforeach; ?>
        </div>
        <?=($more)?'<a class="product__specifications-link" href="productinfo" onclick="$(\'.product__tabs-item[data-toogles=2]\').trigger(\'click\')">Подробнее</a>':''?>
      </div> 
      <div class="product__column addToCartBlock">
	  <?= $this->render($variables, 'catalog/product/main/price/index') ?>

      </div>
    </div>
  </div>
  <div class="product__info-wrap" id="productinfo">
    <div class="center-wrap">
      <div class="product__info">
        <div class="product__tabs toogles__wrap">
          <div class="product__tabs-row mobile--hide">
            <div class="product__tabs-item toogles__item-title toogles__item-title--active" data-toogles="1">Описание</div>
            <?php if($more){ ?><div class="product__tabs-item toogles__item-title" data-toogles="2">Характеристики</div><?php } ?>
            <!-- <div class="product__tabs-item toogles__item-title" data-toogles="3">Отзывы</div> -->
            <div class="product__tabs-item toogles__item-title" data-toogles="3">Доставка и оплата</div>
          </div>
          <div class="product__tabs-slider desktop--hide">
            <div class="swiper-container">
              <div class="swiper-wrapper">
                <div class="swiper-slide">
                  <div class="product__tabs-item toogles__item-title toogles__item-title--active" data-toogles="1">Описание</div>
                </div>
                <div class="swiper-slide">
                  <div class="product__tabs-item toogles__item-title" data-toogles="2">Характеристики</div>
                </div>
                <!-- <div class="swiper-slide">
                  <div class="product__tabs-item toogles__item-title" data-toogles="3">Отзывы</div>
                </div> -->
                <div class="swiper-slide">
                  <div class="product__tabs-item toogles__item-title" data-toogles="3">Доставка и оплата</div>
                </div>
              </div>
            </div>
          </div>
          <div class="toogles__item toogles__item--active" data-toogles="1">
            <div class="toogles__item-content" style="display: block;">
              <div>
                <div class="product__tabs-tab">
                  <div class="article" umi:element-id="<?= $variables['pageId'] ?>"
                      umi:field-name="description" umi:empty="<?= $this->translate('item_description') ?>">
                    <?= $description ?>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div class="toogles__item" data-toogles="2">
            <div class="toogles__item-content">
              <?= $this->render($variables, 'catalog/product/main/properties/index') ?>
            </div>
          </div>
          <!-- <div class="toogles__item" data-toogles="3">
            <div class="toogles__item-content">
              <div>
                <div class="product__tabs-tab">
                  <p>Отзывы</p>
                </div>
              </div>
            </div>
          </div> -->
          <div class="toogles__item" data-toogles="3">
            <div class="toogles__item-content">
              <div>
                <div class="product__tabs-tab">
                <h2>Способы оплаты</h2>
<p>Интернет-магазин NOVOPOOL работает с физическими и с юридическими лицами. Мы предлагаем наличный и безналичный расчет, принимаем банковские карты популярных платежных систем: Visa, Mastercard, МИР.</p>
<h3>Оплата для физических лиц</h3>
<ul>
	<li>В Санкт-Петербурге и Ленинградской области &ndash; наличными при получении товара.</li>
	<li>В других регионах России &ndash; оплата по выставленному счету в любом удобном банке; денежный перевод на карту Сбербанка РФ.</li>
</ul>
<h3>Оплата для юридических лиц</h3>
<ul>
	<li>В Санкт-Петербурге и Ленинградской области &ndash; по безналичному расчету или наличными при оформлении заказа.</li>
	<li>В других регионах России &ndash; по безналичному расчету.</li>
</ul>
<p>Отгрузка товаров проводится при проведении 100 % оплаты.</p>
<h2>Доставка</h2>
<p><strong>Доставка по Санкт-Петербургу</strong> осуществляется в течение 1-5 рабочих дней после оформления заказа при условии наличия товара на складе. Доставка производится ежедневно, включая выходные и праздничные дни (по предварительной договоренности), с 10:00 до 22:00.</p>
<h3>Стоимость доставки по Санкт-Петербургу</h3>
<p>Для заказов стоимостью менее 5 000 руб.:</p>
<ul>
	<li>в пределах КАД: 750 руб.</li>
	<li>за пределами КАД (до 50 км): 1 500 руб.</li>
	<li>за пределами КАД (далее 50 км): 1 500 руб.+ 25 руб./км</li>
</ul>
<p>Для заказов стоимостью более 5 000 руб.:</p>
<ul>
	<li>в пределах КАД: 500 руб.</li>
	<li>за пределами КАД (до 50 км): 1 300 руб.</li>
	<li>за пределами КАД (далее 50 км): 1 000 руб. + 25 руб./км</li>
</ul>
<p>Доставка сборных и каркасных бассейнов:</p>
<ul>
	<li>в пределах КАД: 1 000 руб.<br />за пределами КАД (до 50 км): 2 000 руб.<br />за пределами КАД (далее 50 км): 2 000 руб. + 25 руб./км</li>
</ul>
<h3>Самовывоз</h3>
<p>Самовывоз товара производится по адресу: г. Санкт-Петербург, ул. Бассейная, д. 73, к1, пом. 7. Перед получением заказа, пожалуйста, убедитесь, что он сформирован и находится в пункте выдачи заказов, предварительно позвонив по телефону <span><a class="contacts__link" href="tel:+7 (812) 716-77-11">+7 (812) 716-77-11</a></span> (с 9:00 до 20:00).</p>
<h3>Доставка в другие города России</h3>
<p>В регионах России отгрузка товаров осуществляется посредством транспортных компаний, указанных в заказе. Статус выполнения заявки можно уточнить по телефону <span><a class="contacts__link" href="tel:+7 (812) 716-77-11">+7 (812) 716-77-11</a></span> (с 9:00 до 20:00).</p>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="product__manufacturer mobile--hide">
          <div class="manufacturer anchors"><a class="manufacturer__logo" data-anchors href="<?=$parent->link?>?filter%5Bbrend%5D%5B0%5D=<?=$brand->name?>">
              <div><?=$brand->name?></div></a>
            <p class="manufacturer__text">Получите скидку 3% от суммы заказа</p><a data-anchors class="manufacturer__link" href="<?=$parent->link?>">Все товары категории<br></a><a class="manufacturer__link" href="productinfo" onclick="$('.product__tabs-item[data-toogles=2]').trigger('click')">Все характеристики</a>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

<?php if ($this->isShowCommentsOnProductPage()): ?>
	<?= $this->renderComments($variables) ?>
<?php endif;?>	
<?php
/*
        <div class="wrap-section">
          <section class="kit toogles__wrap">
            <div class="center-wrap">
              <div class="kit__title">
                <div class="kit__title-item toogles__item-title toogles__item-title--active" data-toogles="1">В комплекте дешевле</div>
                <div class="kit__title-item toogles__item-title" data-toogles="2">С этим товаром покупают</div>
              </div>
              <div class="toogles__item toogles__item--active" data-toogles="1">
                <div class="toogles__item-content" style="display: block;">
                  <div>
                    <div class="kit__tab mobile--hide">
                      <div class="kit__tab-item"><a class="card" href="">
                          <p class="card__filter">хит</p>
                          <p class="card__filter card__filter--bg">доставка безплатная</p>
                          <div class="card__img">
                            <div><img src="assets/images/kit__img1.png" alt="">
                            </div>
                          </div>
                          <p class="card__price">25 000 ₽<span class="card__price-old">27 790</span><span class="card__price-discount">-10%</span>
                          </p>
                          <div class="card__title">Фильтровальная установка Kripsol Granada + песок</div>
                          <div class="card__bottom">
                            <div class="basket-wrap">
                              <div class="basket">
                                <svg viewBox="0 0 21 21" fill="none" xmlns="http://www.w3.org/2000/svg">
                                  <path fill-rule="evenodd" clip-rule="evenodd" d="M6.76598 13.5765L6.76934 13.5763H17.9238C18.1984 13.5763 18.4399 13.3941 18.5154 13.1301L20.9763 4.51681C21.0293 4.33112 20.9922 4.13148 20.876 3.97736C20.7597 3.82323 20.5778 3.73254 20.3848 3.73254H5.34709L4.9073 1.75338C4.84465 1.47188 4.59503 1.27161 4.30664 1.27161H0.615234C0.275414 1.27161 0 1.54702 0 1.88684C0 2.22666 0.275414 2.50208 0.615234 2.50208H3.81317L6.03442 12.498C6.21923 13.2621 6.36006 13.5636 6.76598 13.5765ZM17.4597 12.3458L19.5691 4.96301H5.62042L7.26105 12.3458H17.4597Z"></path>
                                  <path d="M6 17C6 18.1028 6.89722 19 8 19C9.10278 19 10 18.1028 10 17C10 15.8972 9.10278 15 8 15C6.89722 15 6 15.8972 6 17ZM8 16.3333C8.36753 16.3333 8.66667 16.6325 8.66667 17C8.66667 17.3675 8.36753 17.6667 8 17.6667C7.63247 17.6667 7.33333 17.3675 7.33333 17C7.33333 16.6325 7.63247 16.3333 8 16.3333Z"></path>
                                  <path d="M15 17C15 18.1028 15.8972 19 17 19C18.1028 19 19 18.1028 19 17C19 15.8972 18.1028 15 17 15C15.8972 15 15 15.8972 15 17ZM17 16.3333C17.3675 16.3333 17.6667 16.6325 17.6667 17C17.6667 17.3675 17.3675 17.6667 17 17.6667C16.6325 17.6667 16.3333 17.3675 16.3333 17C16.3333 16.6325 16.6325 16.3333 17 16.3333Z"></path>
                                </svg><span>В корзину</span>
                              </div>
                            </div>
                            <div class="card__plus">  
                              <svg width="13" height="14" viewBox="0 0 13 14" fill="none" xmlns="http://www.w3.org/2000/svg">
                                <path fill-rule="evenodd" clip-rule="evenodd" d="M0.125 2.25004V0.833374H12.875V2.25004H0.125ZM0.125 7.20837V5.79171H12.875V7.20837H0.125ZM0.125 12.1667V10.75H5.79167V12.1667H0.125ZM12.875 10.75V12.1667H11.1042V13.9375H9.6875V12.1667H7.91667V10.75H9.6875V8.97921H11.1042V10.75H12.875Z"></path>
                              </svg>
                            </div>
                            <div class="card__heart">
                              <svg width="15" height="13" viewBox="0 0 15 13" fill="none" xmlns="http://www.w3.org/2000/svg">
                                <path d="M7.11941 1.92959L7.50008 2.37662L7.88076 1.92959C8.56104 1.13072 9.60647 0.625 10.6876 0.625C12.5931 0.625 14.0834 2.11531 14.0834 4.02083C14.0834 5.19534 13.5597 6.30011 12.5362 7.55141C11.507 8.80972 10.0253 10.1544 8.19129 11.8175L8.19058 11.8182L7.4988 12.4479L6.80926 11.825L6.80834 11.8241C4.97463 10.1578 3.4932 8.81153 2.46404 7.55242C1.44045 6.30014 0.916748 5.19535 0.916748 4.02083C0.916748 2.11531 2.40706 0.625 4.31258 0.625C5.39369 0.625 6.43912 1.13072 7.11941 1.92959Z"></path>
                              </svg>
                            </div>
                          </div></a>
                      </div>
                      <div class="kit__tab-item"><a class="card" href="">
                          <p class="card__filter">хит</p>
                          <p class="card__filter card__filter--bg">доставка безплатная</p>
                          <div class="card__img">
                            <div><img src="assets/images/kit__img2.png" alt="">
                            </div>
                          </div>
                          <p class="card__price">29 000 ₽<span class="card__price-old">31 790</span><span class="card__price-discount">-15%</span>
                          </p>
                          <div class="card__title">Фильтровальная установка Kripsol Granada + стеклянные наполнитель</div>
                          <div class="card__bottom">
                            <div class="basket-wrap">
                              <div class="basket">
                                <svg viewBox="0 0 21 21" fill="none" xmlns="http://www.w3.org/2000/svg">
                                  <path fill-rule="evenodd" clip-rule="evenodd" d="M6.76598 13.5765L6.76934 13.5763H17.9238C18.1984 13.5763 18.4399 13.3941 18.5154 13.1301L20.9763 4.51681C21.0293 4.33112 20.9922 4.13148 20.876 3.97736C20.7597 3.82323 20.5778 3.73254 20.3848 3.73254H5.34709L4.9073 1.75338C4.84465 1.47188 4.59503 1.27161 4.30664 1.27161H0.615234C0.275414 1.27161 0 1.54702 0 1.88684C0 2.22666 0.275414 2.50208 0.615234 2.50208H3.81317L6.03442 12.498C6.21923 13.2621 6.36006 13.5636 6.76598 13.5765ZM17.4597 12.3458L19.5691 4.96301H5.62042L7.26105 12.3458H17.4597Z"></path>
                                  <path d="M6 17C6 18.1028 6.89722 19 8 19C9.10278 19 10 18.1028 10 17C10 15.8972 9.10278 15 8 15C6.89722 15 6 15.8972 6 17ZM8 16.3333C8.36753 16.3333 8.66667 16.6325 8.66667 17C8.66667 17.3675 8.36753 17.6667 8 17.6667C7.63247 17.6667 7.33333 17.3675 7.33333 17C7.33333 16.6325 7.63247 16.3333 8 16.3333Z"></path>
                                  <path d="M15 17C15 18.1028 15.8972 19 17 19C18.1028 19 19 18.1028 19 17C19 15.8972 18.1028 15 17 15C15.8972 15 15 15.8972 15 17ZM17 16.3333C17.3675 16.3333 17.6667 16.6325 17.6667 17C17.6667 17.3675 17.3675 17.6667 17 17.6667C16.6325 17.6667 16.3333 17.3675 16.3333 17C16.3333 16.6325 16.6325 16.3333 17 16.3333Z"></path>
                                </svg><span>В корзину</span>
                              </div>
                            </div>
                            <div class="card__plus">  
                              <svg width="13" height="14" viewBox="0 0 13 14" fill="none" xmlns="http://www.w3.org/2000/svg">
                                <path fill-rule="evenodd" clip-rule="evenodd" d="M0.125 2.25004V0.833374H12.875V2.25004H0.125ZM0.125 7.20837V5.79171H12.875V7.20837H0.125ZM0.125 12.1667V10.75H5.79167V12.1667H0.125ZM12.875 10.75V12.1667H11.1042V13.9375H9.6875V12.1667H7.91667V10.75H9.6875V8.97921H11.1042V10.75H12.875Z"></path>
                              </svg>
                            </div>
                            <div class="card__heart">
                              <svg width="15" height="13" viewBox="0 0 15 13" fill="none" xmlns="http://www.w3.org/2000/svg">
                                <path d="M7.11941 1.92959L7.50008 2.37662L7.88076 1.92959C8.56104 1.13072 9.60647 0.625 10.6876 0.625C12.5931 0.625 14.0834 2.11531 14.0834 4.02083C14.0834 5.19534 13.5597 6.30011 12.5362 7.55141C11.507 8.80972 10.0253 10.1544 8.19129 11.8175L8.19058 11.8182L7.4988 12.4479L6.80926 11.825L6.80834 11.8241C4.97463 10.1578 3.4932 8.81153 2.46404 7.55242C1.44045 6.30014 0.916748 5.19535 0.916748 4.02083C0.916748 2.11531 2.40706 0.625 4.31258 0.625C5.39369 0.625 6.43912 1.13072 7.11941 1.92959Z"></path>
                              </svg>
                            </div>
                          </div></a>
                      </div>
                      <div class="kit__tab-item kit__tab-item--hide"></div>
                      <div class="kit__tab-item kit__tab-item--hide"> </div>
                      <div class="kit__tab-item kit__tab-item--hide"></div>
                    </div>
                    <div class="kit-slider desktop--hide">
                      <div class="swiper-container">
                        <div class="swiper-wrapper">
                          <div class="swiper-slide"><a class="card" href="">
                              <div class="card__img">
                                <div><img src="assets/images/kit__img1.png" alt="">
                                </div>
                              </div>
                              <p class="card__price">1 100 ₽<span class="card__price-old">27 790 ₽</span>
                              </p>
                              <div class="card__price-discount">-15%</div>
                              <div class="card__title">Песок кварцевый фракция 0,5-1,0 мм (мешок 25 кг)</div>
                              <p class="card__article">Артикул:<span>283323</span></p></a>
                          </div>
                          <div class="swiper-slide"><a class="card" href="">
                              <div class="card__img">
                                <div><img src="assets/images/product__slider-img2.png" alt="">
                                </div>
                              </div>
                              <p class="card__price">1 100 ₽<span class="card__price-old"></span>
                              </p>
                              <div class="card__title">Песок кварцевый фракция 0,5-1,0 мм (мешок 25 кг)</div>
                              <p class="card__article">Артикул:<span>283323</span></p></a>
                          </div>
                          <div class="swiper-slide"><a class="card" href="">
                              <div class="card__img">
                                <div><img src="assets/images/product__slider-img2.png" alt="">
                                </div>
                              </div>
                              <p class="card__price">1 100 ₽<span class="card__price-old"></span>
                              </p>
                              <div class="card__title">Песок кварцевый фракция 0,5-1,0 мм (мешок 25 кг)</div>
                              <p class="card__article">Артикул:<span>283323</span></p></a>
                          </div>
                          <div class="swiper-slide"><a class="card" href="">
                              <div class="card__img">
                                <div><img src="assets/images/product__slider-img2.png" alt="">
                                </div>
                              </div>
                              <p class="card__price">1 100 ₽<span class="card__price-old"></span>
                              </p>
                              <div class="card__title">Песок кварцевый фракция 0,5-1,0 мм (мешок 25 кг)</div>
                              <p class="card__article">Артикул:<span>283323</span></p></a>
                          </div>
                          <div class="swiper-slide"><a class="card" href="">
                              <div class="card__img">
                                <div><img src="assets/images/product__slider-img2.png" alt="">
                                </div>
                              </div>
                              <p class="card__price">1 100 ₽<span class="card__price-old"></span>
                              </p>
                              <div class="card__title">Песок кварцевый фракция 0,5-1,0 мм (мешок 25 кг)</div>
                              <p class="card__article">Артикул:<span>283323</span></p></a>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              <div class="toogles__item" data-toogles="2">
                <div class="toogles__item-content">
                  <div>
                    <div class="kit__tab mobile--hide">
                      <div class="kit__tab-item"><a class="card" href="">
                          <p class="card__filter">хит</p>
                          <p class="card__filter card__filter--bg">доставка безплатная</p>
                          <div class="card__img">
                            <div><img src="assets/images/kit__img3.png" alt="">
                            </div>
                          </div>
                          <p class="card__price">1 100 ₽<span class="card__price-old"></span>
                          </p>
                          <div class="card__title">Песок кварцевый фракция 0,5-1,0 мм (мешок 25 кг)</div>
                          <div class="card__bottom">
                            <div class="basket-wrap">
                              <div class="basket">
                                <svg viewBox="0 0 21 21" fill="none" xmlns="http://www.w3.org/2000/svg">
                                  <path fill-rule="evenodd" clip-rule="evenodd" d="M6.76598 13.5765L6.76934 13.5763H17.9238C18.1984 13.5763 18.4399 13.3941 18.5154 13.1301L20.9763 4.51681C21.0293 4.33112 20.9922 4.13148 20.876 3.97736C20.7597 3.82323 20.5778 3.73254 20.3848 3.73254H5.34709L4.9073 1.75338C4.84465 1.47188 4.59503 1.27161 4.30664 1.27161H0.615234C0.275414 1.27161 0 1.54702 0 1.88684C0 2.22666 0.275414 2.50208 0.615234 2.50208H3.81317L6.03442 12.498C6.21923 13.2621 6.36006 13.5636 6.76598 13.5765ZM17.4597 12.3458L19.5691 4.96301H5.62042L7.26105 12.3458H17.4597Z"></path>
                                  <path d="M6 17C6 18.1028 6.89722 19 8 19C9.10278 19 10 18.1028 10 17C10 15.8972 9.10278 15 8 15C6.89722 15 6 15.8972 6 17ZM8 16.3333C8.36753 16.3333 8.66667 16.6325 8.66667 17C8.66667 17.3675 8.36753 17.6667 8 17.6667C7.63247 17.6667 7.33333 17.3675 7.33333 17C7.33333 16.6325 7.63247 16.3333 8 16.3333Z"></path>
                                  <path d="M15 17C15 18.1028 15.8972 19 17 19C18.1028 19 19 18.1028 19 17C19 15.8972 18.1028 15 17 15C15.8972 15 15 15.8972 15 17ZM17 16.3333C17.3675 16.3333 17.6667 16.6325 17.6667 17C17.6667 17.3675 17.3675 17.6667 17 17.6667C16.6325 17.6667 16.3333 17.3675 16.3333 17C16.3333 16.6325 16.6325 16.3333 17 16.3333Z"></path>
                                </svg><span>В корзину</span>
                              </div>
                            </div>
                            <div class="card__plus">  
                              <svg width="13" height="14" viewBox="0 0 13 14" fill="none" xmlns="http://www.w3.org/2000/svg">
                                <path fill-rule="evenodd" clip-rule="evenodd" d="M0.125 2.25004V0.833374H12.875V2.25004H0.125ZM0.125 7.20837V5.79171H12.875V7.20837H0.125ZM0.125 12.1667V10.75H5.79167V12.1667H0.125ZM12.875 10.75V12.1667H11.1042V13.9375H9.6875V12.1667H7.91667V10.75H9.6875V8.97921H11.1042V10.75H12.875Z"></path>
                              </svg>
                            </div>
                            <div class="card__heart">
                              <svg width="15" height="13" viewBox="0 0 15 13" fill="none" xmlns="http://www.w3.org/2000/svg">
                                <path d="M7.11941 1.92959L7.50008 2.37662L7.88076 1.92959C8.56104 1.13072 9.60647 0.625 10.6876 0.625C12.5931 0.625 14.0834 2.11531 14.0834 4.02083C14.0834 5.19534 13.5597 6.30011 12.5362 7.55141C11.507 8.80972 10.0253 10.1544 8.19129 11.8175L8.19058 11.8182L7.4988 12.4479L6.80926 11.825L6.80834 11.8241C4.97463 10.1578 3.4932 8.81153 2.46404 7.55242C1.44045 6.30014 0.916748 5.19535 0.916748 4.02083C0.916748 2.11531 2.40706 0.625 4.31258 0.625C5.39369 0.625 6.43912 1.13072 7.11941 1.92959Z"></path>
                              </svg>
                            </div>
                          </div>
                          <p class="card__article">Артикул:<span>283323</span></p></a>
                      </div>
                      <div class="kit__tab-item"><a class="card" href="">
                          <p class="card__filter">хит</p>
                          <p class="card__filter card__filter--bg">доставка безплатная</p>
                          <div class="card__img">
                            <div><img src="assets/images/kit__img4.png" alt="">
                            </div>
                          </div>
                          <p class="card__price">3 413 ₽<span class="card__price-old"></span>
                          </p>
                          <div class="card__title">Стеклянный фильтрующий наполнитель для песчаных фильтров Nature Works</div>
                          <div class="card__bottom">
                            <div class="basket-wrap">
                              <div class="basket">
                                <svg viewBox="0 0 21 21" fill="none" xmlns="http://www.w3.org/2000/svg">
                                  <path fill-rule="evenodd" clip-rule="evenodd" d="M6.76598 13.5765L6.76934 13.5763H17.9238C18.1984 13.5763 18.4399 13.3941 18.5154 13.1301L20.9763 4.51681C21.0293 4.33112 20.9922 4.13148 20.876 3.97736C20.7597 3.82323 20.5778 3.73254 20.3848 3.73254H5.34709L4.9073 1.75338C4.84465 1.47188 4.59503 1.27161 4.30664 1.27161H0.615234C0.275414 1.27161 0 1.54702 0 1.88684C0 2.22666 0.275414 2.50208 0.615234 2.50208H3.81317L6.03442 12.498C6.21923 13.2621 6.36006 13.5636 6.76598 13.5765ZM17.4597 12.3458L19.5691 4.96301H5.62042L7.26105 12.3458H17.4597Z"></path>
                                  <path d="M6 17C6 18.1028 6.89722 19 8 19C9.10278 19 10 18.1028 10 17C10 15.8972 9.10278 15 8 15C6.89722 15 6 15.8972 6 17ZM8 16.3333C8.36753 16.3333 8.66667 16.6325 8.66667 17C8.66667 17.3675 8.36753 17.6667 8 17.6667C7.63247 17.6667 7.33333 17.3675 7.33333 17C7.33333 16.6325 7.63247 16.3333 8 16.3333Z"></path>
                                  <path d="M15 17C15 18.1028 15.8972 19 17 19C18.1028 19 19 18.1028 19 17C19 15.8972 18.1028 15 17 15C15.8972 15 15 15.8972 15 17ZM17 16.3333C17.3675 16.3333 17.6667 16.6325 17.6667 17C17.6667 17.3675 17.3675 17.6667 17 17.6667C16.6325 17.6667 16.3333 17.3675 16.3333 17C16.3333 16.6325 16.6325 16.3333 17 16.3333Z"></path>
                                </svg><span>В корзину</span>
                              </div>
                            </div>
                            <div class="card__plus">  
                              <svg width="13" height="14" viewBox="0 0 13 14" fill="none" xmlns="http://www.w3.org/2000/svg">
                                <path fill-rule="evenodd" clip-rule="evenodd" d="M0.125 2.25004V0.833374H12.875V2.25004H0.125ZM0.125 7.20837V5.79171H12.875V7.20837H0.125ZM0.125 12.1667V10.75H5.79167V12.1667H0.125ZM12.875 10.75V12.1667H11.1042V13.9375H9.6875V12.1667H7.91667V10.75H9.6875V8.97921H11.1042V10.75H12.875Z"></path>
                              </svg>
                            </div>
                            <div class="card__heart">
                              <svg width="15" height="13" viewBox="0 0 15 13" fill="none" xmlns="http://www.w3.org/2000/svg">
                                <path d="M7.11941 1.92959L7.50008 2.37662L7.88076 1.92959C8.56104 1.13072 9.60647 0.625 10.6876 0.625C12.5931 0.625 14.0834 2.11531 14.0834 4.02083C14.0834 5.19534 13.5597 6.30011 12.5362 7.55141C11.507 8.80972 10.0253 10.1544 8.19129 11.8175L8.19058 11.8182L7.4988 12.4479L6.80926 11.825L6.80834 11.8241C4.97463 10.1578 3.4932 8.81153 2.46404 7.55242C1.44045 6.30014 0.916748 5.19535 0.916748 4.02083C0.916748 2.11531 2.40706 0.625 4.31258 0.625C5.39369 0.625 6.43912 1.13072 7.11941 1.92959Z"></path>
                              </svg>
                            </div>
                          </div>
                          <p class="card__article">Артикул:<span>283323</span></p></a>
                      </div>
                      <div class="kit__tab-item kit__tab-item--hide"></div>
                      <div class="kit__tab-item kit__tab-item--hide"></div>
                      <div class="kit__tab-item kit__tab-item--hide"></div>
                    </div>
                    <div class="kit-slider desktop--hide">
                      <div class="swiper-container">
                        <div class="swiper-wrapper">
                          <div class="swiper-slide"><a class="card" href="">
                              <div class="card__img">
                                <div><img src="assets/images/kit__img1.png" alt="">
                                </div>
                              </div>
                              <p class="card__price">1 100 ₽<span class="card__price-old">37 790 ₽</span>
                              </p>
                              <div class="card__price-discount">-15%</div>
                              <div class="card__title">Песок кварцевый фракция 0,5-1,0 мм (мешок 25 кг)</div>
                              <p class="card__article">Артикул:<span>283323</span></p></a>
                          </div>
                          <div class="swiper-slide"><a class="card" href="">
                              <div class="card__img">
                                <div><img src="assets/images/product__slider-img2.png" alt="">
                                </div>
                              </div>
                              <p class="card__price">1 100 ₽<span class="card__price-old"></span>
                              </p>
                              <div class="card__title">Песок кварцевый фракция 0,5-1,0 мм (мешок 25 кг)</div>
                              <p class="card__article">Артикул:<span>283323</span></p></a>
                          </div>
                          <div class="swiper-slide"><a class="card" href="">
                              <div class="card__img">
                                <div><img src="assets/images/product__slider-img2.png" alt="">
                                </div>
                              </div>
                              <p class="card__price">1 100 ₽<span class="card__price-old"></span>
                              </p>
                              <div class="card__title">Песок кварцевый фракция 0,5-1,0 мм (мешок 25 кг)</div>
                              <p class="card__article">Артикул:<span>283323</span></p></a>
                          </div>
                          <div class="swiper-slide"><a class="card" href="">
                              <div class="card__img">
                                <div><img src="assets/images/product__slider-img2.png" alt="">
                                </div>
                              </div>
                              <p class="card__price">1 100 ₽<span class="card__price-old"></span>
                              </p>
                              <div class="card__title">Песок кварцевый фракция 0,5-1,0 мм (мешок 25 кг)</div>
                              <p class="card__article">Артикул:<span>283323</span></p></a>
                          </div>
                          <div class="swiper-slide"><a class="card" href="">
                              <div class="card__img">
                                <div><img src="assets/images/product__slider-img2.png" alt="">
                                </div>
                              </div>
                              <p class="card__price">1 100 ₽<span class="card__price-old"></span>
                              </p>
                              <div class="card__title">Песок кварцевый фракция 0,5-1,0 мм (мешок 25 кг)</div>
                              <p class="card__article">Артикул:<span>283323</span></p></a>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </section>
<article class="articles">
  <div class="center-wrap">
    <div class="simple-title articles__title">Статьи</div>
    <div class="articles__wrap mobile--hide"><a class="articles__img" href="">
        <div><img src="assets/images/article__img.png" alt=""></div></a>
      <div class="articles__content">
        <p class="articles__content-descr">Про оборудование — 05.09.2020</p>
        <div class="articles__content-title">Фильтры для бассейна: виды, советы по выбору и использованию</div>
        <p class="articles__content-text">Для того чтобы вода в бассейне была чистой и свежей, тем самым доставляла удовольствие купающимся, необходима система фильтрации. При отсутствии фильтров в искусственном водоеме вода будет мутной, иногда зеленой или с белым налетом.</p>
      </div>
    </div>
    <div class="articles-slider desktop--hide">
      <div class="swiper-container">
        <div class="swiper-wrapper">
          <div class="swiper-slide">
            <div class="articles__wrap"><a class="articles__img" href="">
                <div><img src="assets/images/article__img.png" alt=""></div></a>
              <div class="articles__content">
                <p class="articles__content-descr">Про оборудование — 05.09.2020</p>
                <div class="articles__content-title">Фильтры для бассейна: виды, советы по выбору и использованию</div>
                <p class="articles__content-text">Для того чтобы вода в бассейне была чистой и свежей, тем самым доставляла удовольствие купающимся, необходима система фильтрации. При отсутствии фильтров в искусственном водоеме вода будет мутной, иногда зеленой или с белым налетом.</p>
              </div>
            </div>
          </div>
          <div class="swiper-slide">
            <div class="articles__wrap"><a class="articles__img" href="">
                <div><img src="assets/images/article__img.png" alt=""></div></a>
              <div class="articles__content">
                <p class="articles__content-descr">Про оборудование — 05.09.2020</p>
                <div class="articles__content-title">Фильтры для бассейна: виды, советы по выбору и использованию</div>
                <p class="articles__content-text">Для того чтобы вода в бассейне была чистой и свежей, тем самым доставляла удовольствие купающимся, необходима система фильтрации. При отсутствии фильтров в искусственном водоеме вода будет мутной, иногда зеленой или с белым налетом.</p>
              </div>
            </div>
          </div>
          <div class="swiper-slide">
            <div class="articles__wrap"><a class="articles__img" href="">
                <div><img src="assets/images/article__img.png" alt=""></div></a>
              <div class="articles__content">
                <p class="articles__content-descr">Про оборудование — 05.09.2020</p>
                <div class="articles__content-title">Фильтры для бассейна: виды, советы по выбору и использованию</div>
                <p class="articles__content-text">Для того чтобы вода в бассейне была чистой и свежей, тем самым доставляла удовольствие купающимся, необходима система фильтрации. При отсутствии фильтров в искусственном водоеме вода будет мутной, иногда зеленой или с белым налетом.</p>
              </div>
            </div>
          </div>
          <div class="swiper-slide">
            <div class="articles__wrap"><a class="articles__img" href="">
                <div><img src="assets/images/article__img.png" alt=""></div></a>
              <div class="articles__content">
                <p class="articles__content-descr">Про оборудование — 05.09.2020</p>
                <div class="articles__content-title">Фильтры для бассейна: виды, советы по выбору и использованию</div>
                <p class="articles__content-text">Для того чтобы вода в бассейне была чистой и свежей, тем самым доставляла удовольствие купающимся, необходима система фильтрации. При отсутствии фильтров в искусственном водоеме вода будет мутной, иногда зеленой или с белым налетом.  </p>
              </div>
            </div>
          </div>
        </div>
        <!-- Add Pagination-->
      </div>
      <div class="swiper-pagination"></div>
    </div>
  </div>
</article>

        </div>
        <section class="collection collection--product">
          <div class="center-wrap">
            <div class="simple-title collection__title">Коллекции</div>
            <div class="collection__list mobile--hide"><a class="collection__item" href="">
                <div class="collection__img">
                  <div><img src="assets/images/collection__img3.png" alt=""></div><span class="collection__img-oval"></span>
                </div>
                <div class="collection__item-title">Испанская фильтрация 2020 года</div></a><a class="collection__item collection__item--hide" href=""></a><a class="collection__item collection__item--hide" href=""></a><a class="collection__item collection__item--hide" href=""></a><a class="collection__item collection__item--hide" href=""></a>
            </div>
            <div class="collection-slider desktop--hide">
              <div class="swiper-container">
                <div class="swiper-wrapper">
                  <div class="swiper-slide">
                    <div class="collection__item">
                      <div class="collection__img">
                        <div><img src="assets/images/collection__img3.png" alt=""></div><span class="collection__img-oval"></span>
                      </div><a class="collection__item-title" href="">Испанская фильтрация 2020 года</a>
                    </div>
                  </div>
                  <div class="swiper-slide">
                    <div class="collection__item">
                      <div class="collection__img">
                        <div><img src="assets/images/collection__img3.png" alt=""></div><span class="collection__img-oval"></span>
                      </div><a class="collection__item-title" href="">Испанская фильтрация 2020 года</a>
                    </div>
                  </div>
                  <div class="swiper-slide">
                    <div class="collection__item">
                      <div class="collection__img">
                        <div><img src="assets/images/collection__img3.png" alt=""></div><span class="collection__img-oval"></span>
                      </div><a class="collection__item-title" href="">Испанская фильтрация 2020 года</a>
                    </div>
                  </div>
                  <div class="swiper-slide">
                    <div class="collection__item">
                      <div class="collection__img">
                        <div><img src="assets/images/collection__img3.png" alt=""></div><span class="collection__img-oval"></span>
                      </div><a class="collection__item-title" href="">Испанская фильтрация 2020 года</a>
                    </div>
                  </div>
                  <div class="swiper-slide">
                    <div class="collection__item">
                      <div class="collection__img">
                        <div><img src="assets/images/collection__img3.png" alt=""></div><span class="collection__img-oval"></span>
                      </div><a class="collection__item-title" href="">Испанская фильтрация 2020 года</a>
                    </div>
                  </div>
                  <div class="swiper-slide">
                    <div class="collection__item">
                      <div class="collection__img">
                        <div><img src="assets/images/collection__img3.png" alt=""></div><span class="collection__img-oval"></span>
                      </div><a class="collection__item-title" href="">Испанская фильтрация 2020 года</a>
                    </div>
                  </div>
                  <div class="swiper-slide">
                    <div class="collection__item">
                      <div class="collection__img">
                        <div><img src="assets/images/collection__img3.png" alt=""></div><span class="collection__img-oval"></span>
                      </div><a class="collection__item-title" href="">Испанская фильтрация 2020 года</a>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>
*/ ?>
        <?= $this->render($variables, 'catalog/product/main/see_more/suggested_product_list') ?>
			<?= $this->render($variables, 'catalog/product/main/see_more/related_product_list') ?>

      <?=$this->render($variables, 'catalog/blocks/recently') ?>