<?php
/**
 * Изображение и слайдер.
 *
 * @var umiTemplaterPHP|ViewPhpExtension|DemomarketPhpExtension $this
 * @var array $variables
 */

$imageList = $this->getProductImageList($variables['page']);
/** @var iUmiHierarchyElement $page */
$page = $variables['page'];
?>


<div class="product__slider">
<div class="swiper-container">
	<div class="swiper-wrapper"> 
	<?php $i=1; foreach ($imageList as $image): ?>
		<div class="swiper-slide">
			<div class="product__slider-img toogles__item-title" data-toogles="<?=$i++?>">
				<div><img src="<?= $image ?>" alt=""></div>
			</div>
		</div>
	<?php endforeach; ?>
	</div>
</div>
<div class="swiper-pagination"></div>
</div>